version: '3'

tasks:
  default:
    desc: Run Makefile default target
    cmds:
      - make

  help:
    desc: Display Makefile help
    cmds:
      - make help

  make:
    desc: Run any Makefile target (example: task make -- test)
    cmds:
      - make {{.CLI_ARGS}}
