apiVersion: v1
kind: Service
metadata:
  name: messaging
spec:
  clusterIP: None  # headless service for StatefulSet
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
  selector:
    app: messaging
