apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: messaging
spec:
  serviceName: messaging
  replicas: 1
  selector:
    matchLabels:
      app: messaging
  template:
    metadata:
      labels:
        app: messaging
    spec:
      containers:
        - name: mosquitto
          image: "ghcr.io/esa-philab/yass/eclipse-mosquitto:latest"
          imagePullPolicy: "Always"  # TODO
          ports:
            - containerPort: 1883
              name: mqtt

              # TODO
#          livenessProbe:
#            tcpSocket:
#              port: 1883
#            initialDelaySeconds: 10
#            periodSeconds: 30
#          readinessProbe:
#            tcpSocket:
#              port: 1883
#            initialDelaySeconds: 5
#            periodSeconds: 10
