apiVersion: apps/v1
kind: Deployment
metadata:
  name: yass-web-ui
  labels:
    app: yass-web-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yass-web-ui
  template:
    metadata:
      labels:
        app: yass-web-ui
    spec:
      serviceAccountName: yass-experiment-sa
      containers:
      - name: yass-web-ui
        image: ghcr.io/duobitx/yass-web-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
