// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agend_exp_end_request.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_agend_5fexp_5fend_5frequest_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_agend_5fexp_5fend_5frequest_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_agend_5fexp_5fend_5frequest_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_agend_5fexp_5fend_5frequest_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_agend_5fexp_5fend_5frequest_2eproto;
namespace yass {
namespace fs {
class AgentExperimentEndRequest;
struct AgentExperimentEndRequestDefaultTypeInternal;
extern AgentExperimentEndRequestDefaultTypeInternal _AgentExperimentEndRequest_default_instance_;
}  // namespace fs
}  // namespace yass
PROTOBUF_NAMESPACE_OPEN
template<> ::yass::fs::AgentExperimentEndRequest* Arena::CreateMaybeMessage<::yass::fs::AgentExperimentEndRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace yass {
namespace fs {

enum Status : int {
  EXPERIMENT_END_REQUEST_SUCCESS = 0,
  EXPERIMENT_END_REQUEST_FAILURE = 1,
  Status_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Status_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Status_IsValid(int value);
constexpr Status Status_MIN = EXPERIMENT_END_REQUEST_SUCCESS;
constexpr Status Status_MAX = EXPERIMENT_END_REQUEST_FAILURE;
constexpr int Status_ARRAYSIZE = Status_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Status_descriptor();
template<typename T>
inline const std::string& Status_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Status>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Status_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Status_descriptor(), enum_t_value);
}
inline bool Status_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Status* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Status>(
    Status_descriptor(), name, value);
}
// ===================================================================

class AgentExperimentEndRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yass.fs.AgentExperimentEndRequest) */ {
 public:
  inline AgentExperimentEndRequest() : AgentExperimentEndRequest(nullptr) {}
  ~AgentExperimentEndRequest() override;
  explicit PROTOBUF_CONSTEXPR AgentExperimentEndRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AgentExperimentEndRequest(const AgentExperimentEndRequest& from);
  AgentExperimentEndRequest(AgentExperimentEndRequest&& from) noexcept
    : AgentExperimentEndRequest() {
    *this = ::std::move(from);
  }

  inline AgentExperimentEndRequest& operator=(const AgentExperimentEndRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline AgentExperimentEndRequest& operator=(AgentExperimentEndRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AgentExperimentEndRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const AgentExperimentEndRequest* internal_default_instance() {
    return reinterpret_cast<const AgentExperimentEndRequest*>(
               &_AgentExperimentEndRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AgentExperimentEndRequest& a, AgentExperimentEndRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(AgentExperimentEndRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AgentExperimentEndRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AgentExperimentEndRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AgentExperimentEndRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AgentExperimentEndRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AgentExperimentEndRequest& from) {
    AgentExperimentEndRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AgentExperimentEndRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yass.fs.AgentExperimentEndRequest";
  }
  protected:
  explicit AgentExperimentEndRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCommentFieldNumber = 2,
    kStatusFieldNumber = 1,
  };
  // string comment = 2;
  void clear_comment();
  const std::string& comment() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_comment(ArgT0&& arg0, ArgT... args);
  std::string* mutable_comment();
  PROTOBUF_NODISCARD std::string* release_comment();
  void set_allocated_comment(std::string* comment);
  private:
  const std::string& _internal_comment() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_comment(const std::string& value);
  std::string* _internal_mutable_comment();
  public:

  // .yass.fs.Status status = 1;
  void clear_status();
  ::yass::fs::Status status() const;
  void set_status(::yass::fs::Status value);
  private:
  ::yass::fs::Status _internal_status() const;
  void _internal_set_status(::yass::fs::Status value);
  public:

  // @@protoc_insertion_point(class_scope:yass.fs.AgentExperimentEndRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr comment_;
    int status_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_agend_5fexp_5fend_5frequest_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AgentExperimentEndRequest

// .yass.fs.Status status = 1;
inline void AgentExperimentEndRequest::clear_status() {
  _impl_.status_ = 0;
}
inline ::yass::fs::Status AgentExperimentEndRequest::_internal_status() const {
  return static_cast< ::yass::fs::Status >(_impl_.status_);
}
inline ::yass::fs::Status AgentExperimentEndRequest::status() const {
  // @@protoc_insertion_point(field_get:yass.fs.AgentExperimentEndRequest.status)
  return _internal_status();
}
inline void AgentExperimentEndRequest::_internal_set_status(::yass::fs::Status value) {
  
  _impl_.status_ = value;
}
inline void AgentExperimentEndRequest::set_status(::yass::fs::Status value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:yass.fs.AgentExperimentEndRequest.status)
}

// string comment = 2;
inline void AgentExperimentEndRequest::clear_comment() {
  _impl_.comment_.ClearToEmpty();
}
inline const std::string& AgentExperimentEndRequest::comment() const {
  // @@protoc_insertion_point(field_get:yass.fs.AgentExperimentEndRequest.comment)
  return _internal_comment();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void AgentExperimentEndRequest::set_comment(ArgT0&& arg0, ArgT... args) {
 
 _impl_.comment_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:yass.fs.AgentExperimentEndRequest.comment)
}
inline std::string* AgentExperimentEndRequest::mutable_comment() {
  std::string* _s = _internal_mutable_comment();
  // @@protoc_insertion_point(field_mutable:yass.fs.AgentExperimentEndRequest.comment)
  return _s;
}
inline const std::string& AgentExperimentEndRequest::_internal_comment() const {
  return _impl_.comment_.Get();
}
inline void AgentExperimentEndRequest::_internal_set_comment(const std::string& value) {
  
  _impl_.comment_.Set(value, GetArenaForAllocation());
}
inline std::string* AgentExperimentEndRequest::_internal_mutable_comment() {
  
  return _impl_.comment_.Mutable(GetArenaForAllocation());
}
inline std::string* AgentExperimentEndRequest::release_comment() {
  // @@protoc_insertion_point(field_release:yass.fs.AgentExperimentEndRequest.comment)
  return _impl_.comment_.Release();
}
inline void AgentExperimentEndRequest::set_allocated_comment(std::string* comment) {
  if (comment != nullptr) {
    
  } else {
    
  }
  _impl_.comment_.SetAllocated(comment, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.comment_.IsDefault()) {
    _impl_.comment_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:yass.fs.AgentExperimentEndRequest.comment)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace fs
}  // namespace yass

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::yass::fs::Status> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::yass::fs::Status>() {
  return ::yass::fs::Status_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_agend_5fexp_5fend_5frequest_2eproto
