// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fs_node_geo_update.proto

#include "fs_node_geo_update.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace yass {
namespace fs {
PROTOBUF_CONSTEXPR FsNodeUpdate::FsNodeUpdate(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.network_params_)*/{}
  , /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.pos_str_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.in_shadow_)*/false
  , /*decltype(_impl_.x_)*/0
  , /*decltype(_impl_.y_)*/0
  , /*decltype(_impl_.z_)*/0
  , /*decltype(_impl_.lat_)*/0
  , /*decltype(_impl_.lng_)*/0
  , /*decltype(_impl_.updated_unix_millis_)*/int64_t{0}
  , /*decltype(_impl_.alt_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct FsNodeUpdateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FsNodeUpdateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FsNodeUpdateDefaultTypeInternal() {}
  union {
    FsNodeUpdate _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FsNodeUpdateDefaultTypeInternal _FsNodeUpdate_default_instance_;
PROTOBUF_CONSTEXPR FsNodeUpdateNetworkParamEntry::FsNodeUpdateNetworkParamEntry(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.ip_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.subject_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.distance_)*/0
  , /*decltype(_impl_.package_delay_)*/0
  , /*decltype(_impl_.package_loss_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct FsNodeUpdateNetworkParamEntryDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FsNodeUpdateNetworkParamEntryDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FsNodeUpdateNetworkParamEntryDefaultTypeInternal() {}
  union {
    FsNodeUpdateNetworkParamEntry _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FsNodeUpdateNetworkParamEntryDefaultTypeInternal _FsNodeUpdateNetworkParamEntry_default_instance_;
}  // namespace fs
}  // namespace yass
static ::_pb::Metadata file_level_metadata_fs_5fnode_5fgeo_5fupdate_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_fs_5fnode_5fgeo_5fupdate_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_fs_5fnode_5fgeo_5fupdate_2eproto = nullptr;

const uint32_t TableStruct_fs_5fnode_5fgeo_5fupdate_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yass::fs::FsNodeUpdate, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yass::fs::FsNodeUpdate, _impl_.name_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::FsNodeUpdate, _impl_.in_shadow_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::FsNodeUpdate, _impl_.pos_str_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::FsNodeUpdate, _impl_.x_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::FsNodeUpdate, _impl_.y_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::FsNodeUpdate, _impl_.z_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::FsNodeUpdate, _impl_.lat_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::FsNodeUpdate, _impl_.lng_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::FsNodeUpdate, _impl_.alt_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::FsNodeUpdate, _impl_.network_params_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::FsNodeUpdate, _impl_.updated_unix_millis_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yass::fs::FsNodeUpdateNetworkParamEntry, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yass::fs::FsNodeUpdateNetworkParamEntry, _impl_.ip_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::FsNodeUpdateNetworkParamEntry, _impl_.distance_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::FsNodeUpdateNetworkParamEntry, _impl_.package_delay_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::FsNodeUpdateNetworkParamEntry, _impl_.package_loss_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::FsNodeUpdateNetworkParamEntry, _impl_.subject_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::yass::fs::FsNodeUpdate)},
  { 17, -1, -1, sizeof(::yass::fs::FsNodeUpdateNetworkParamEntry)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::yass::fs::_FsNodeUpdate_default_instance_._instance,
  &::yass::fs::_FsNodeUpdateNetworkParamEntry_default_instance_._instance,
};

const char descriptor_table_protodef_fs_5fnode_5fgeo_5fupdate_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\030fs_node_geo_update.proto\022\007yass.fs\"\345\001\n\014"
  "FsNodeUpdate\022\014\n\004name\030\001 \001(\t\022\021\n\tin_shadow\030"
  "\002 \001(\010\022\017\n\007pos_str\030\003 \001(\t\022\t\n\001x\030\004 \001(\002\022\t\n\001y\030\005"
  " \001(\002\022\t\n\001z\030\006 \001(\002\022\013\n\003lat\030\007 \001(\002\022\013\n\003lng\030\010 \001("
  "\002\022\013\n\003alt\030\t \001(\002\022>\n\016network_params\030\n \003(\0132&"
  ".yass.fs.FsNodeUpdateNetworkParamEntry\022\033"
  "\n\023updated_unix_millis\030\013 \001(\003\"{\n\035FsNodeUpd"
  "ateNetworkParamEntry\022\n\n\002ip\030\001 \001(\t\022\020\n\010dist"
  "ance\030\002 \001(\002\022\025\n\rpackage_delay\030\003 \001(\002\022\024\n\014pac"
  "kage_loss\030\004 \001(\002\022\017\n\007subject\030\005 \001(\tBCZAgith"
  "ub.com/duobitx/yass-internal-components/"
  "go-common/proto;protob\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_fs_5fnode_5fgeo_5fupdate_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_fs_5fnode_5fgeo_5fupdate_2eproto = {
    false, false, 469, descriptor_table_protodef_fs_5fnode_5fgeo_5fupdate_2eproto,
    "fs_node_geo_update.proto",
    &descriptor_table_fs_5fnode_5fgeo_5fupdate_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_fs_5fnode_5fgeo_5fupdate_2eproto::offsets,
    file_level_metadata_fs_5fnode_5fgeo_5fupdate_2eproto, file_level_enum_descriptors_fs_5fnode_5fgeo_5fupdate_2eproto,
    file_level_service_descriptors_fs_5fnode_5fgeo_5fupdate_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_fs_5fnode_5fgeo_5fupdate_2eproto_getter() {
  return &descriptor_table_fs_5fnode_5fgeo_5fupdate_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_fs_5fnode_5fgeo_5fupdate_2eproto(&descriptor_table_fs_5fnode_5fgeo_5fupdate_2eproto);
namespace yass {
namespace fs {

// ===================================================================

class FsNodeUpdate::_Internal {
 public:
};

FsNodeUpdate::FsNodeUpdate(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:yass.fs.FsNodeUpdate)
}
FsNodeUpdate::FsNodeUpdate(const FsNodeUpdate& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  FsNodeUpdate* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.network_params_){from._impl_.network_params_}
    , decltype(_impl_.name_){}
    , decltype(_impl_.pos_str_){}
    , decltype(_impl_.in_shadow_){}
    , decltype(_impl_.x_){}
    , decltype(_impl_.y_){}
    , decltype(_impl_.z_){}
    , decltype(_impl_.lat_){}
    , decltype(_impl_.lng_){}
    , decltype(_impl_.updated_unix_millis_){}
    , decltype(_impl_.alt_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.pos_str_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.pos_str_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_pos_str().empty()) {
    _this->_impl_.pos_str_.Set(from._internal_pos_str(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.in_shadow_, &from._impl_.in_shadow_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.alt_) -
    reinterpret_cast<char*>(&_impl_.in_shadow_)) + sizeof(_impl_.alt_));
  // @@protoc_insertion_point(copy_constructor:yass.fs.FsNodeUpdate)
}

inline void FsNodeUpdate::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.network_params_){arena}
    , decltype(_impl_.name_){}
    , decltype(_impl_.pos_str_){}
    , decltype(_impl_.in_shadow_){false}
    , decltype(_impl_.x_){0}
    , decltype(_impl_.y_){0}
    , decltype(_impl_.z_){0}
    , decltype(_impl_.lat_){0}
    , decltype(_impl_.lng_){0}
    , decltype(_impl_.updated_unix_millis_){int64_t{0}}
    , decltype(_impl_.alt_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.pos_str_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.pos_str_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

FsNodeUpdate::~FsNodeUpdate() {
  // @@protoc_insertion_point(destructor:yass.fs.FsNodeUpdate)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void FsNodeUpdate::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.network_params_.~RepeatedPtrField();
  _impl_.name_.Destroy();
  _impl_.pos_str_.Destroy();
}

void FsNodeUpdate::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void FsNodeUpdate::Clear() {
// @@protoc_insertion_point(message_clear_start:yass.fs.FsNodeUpdate)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.network_params_.Clear();
  _impl_.name_.ClearToEmpty();
  _impl_.pos_str_.ClearToEmpty();
  ::memset(&_impl_.in_shadow_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.alt_) -
      reinterpret_cast<char*>(&_impl_.in_shadow_)) + sizeof(_impl_.alt_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FsNodeUpdate::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "yass.fs.FsNodeUpdate.name"));
        } else
          goto handle_unusual;
        continue;
      // bool in_shadow = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.in_shadow_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string pos_str = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_pos_str();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "yass.fs.FsNodeUpdate.pos_str"));
        } else
          goto handle_unusual;
        continue;
      // float x = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 37)) {
          _impl_.x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float y = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 45)) {
          _impl_.y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float z = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 53)) {
          _impl_.z_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float lat = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 61)) {
          _impl_.lat_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float lng = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 69)) {
          _impl_.lng_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float alt = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 77)) {
          _impl_.alt_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // repeated .yass.fs.FsNodeUpdateNetworkParamEntry network_params = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_network_params(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<82>(ptr));
        } else
          goto handle_unusual;
        continue;
      // int64 updated_unix_millis = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 88)) {
          _impl_.updated_unix_millis_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* FsNodeUpdate::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yass.fs.FsNodeUpdate)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yass.fs.FsNodeUpdate.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // bool in_shadow = 2;
  if (this->_internal_in_shadow() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_in_shadow(), target);
  }

  // string pos_str = 3;
  if (!this->_internal_pos_str().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_pos_str().data(), static_cast<int>(this->_internal_pos_str().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yass.fs.FsNodeUpdate.pos_str");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_pos_str(), target);
  }

  // float x = 4;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_x = this->_internal_x();
  uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(4, this->_internal_x(), target);
  }

  // float y = 5;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_y = this->_internal_y();
  uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(5, this->_internal_y(), target);
  }

  // float z = 6;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_z = this->_internal_z();
  uint32_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(6, this->_internal_z(), target);
  }

  // float lat = 7;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_lat = this->_internal_lat();
  uint32_t raw_lat;
  memcpy(&raw_lat, &tmp_lat, sizeof(tmp_lat));
  if (raw_lat != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(7, this->_internal_lat(), target);
  }

  // float lng = 8;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_lng = this->_internal_lng();
  uint32_t raw_lng;
  memcpy(&raw_lng, &tmp_lng, sizeof(tmp_lng));
  if (raw_lng != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(8, this->_internal_lng(), target);
  }

  // float alt = 9;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_alt = this->_internal_alt();
  uint32_t raw_alt;
  memcpy(&raw_alt, &tmp_alt, sizeof(tmp_alt));
  if (raw_alt != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(9, this->_internal_alt(), target);
  }

  // repeated .yass.fs.FsNodeUpdateNetworkParamEntry network_params = 10;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_network_params_size()); i < n; i++) {
    const auto& repfield = this->_internal_network_params(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(10, repfield, repfield.GetCachedSize(), target, stream);
  }

  // int64 updated_unix_millis = 11;
  if (this->_internal_updated_unix_millis() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(11, this->_internal_updated_unix_millis(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yass.fs.FsNodeUpdate)
  return target;
}

size_t FsNodeUpdate::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yass.fs.FsNodeUpdate)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .yass.fs.FsNodeUpdateNetworkParamEntry network_params = 10;
  total_size += 1UL * this->_internal_network_params_size();
  for (const auto& msg : this->_impl_.network_params_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // string pos_str = 3;
  if (!this->_internal_pos_str().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_pos_str());
  }

  // bool in_shadow = 2;
  if (this->_internal_in_shadow() != 0) {
    total_size += 1 + 1;
  }

  // float x = 4;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_x = this->_internal_x();
  uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    total_size += 1 + 4;
  }

  // float y = 5;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_y = this->_internal_y();
  uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    total_size += 1 + 4;
  }

  // float z = 6;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_z = this->_internal_z();
  uint32_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    total_size += 1 + 4;
  }

  // float lat = 7;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_lat = this->_internal_lat();
  uint32_t raw_lat;
  memcpy(&raw_lat, &tmp_lat, sizeof(tmp_lat));
  if (raw_lat != 0) {
    total_size += 1 + 4;
  }

  // float lng = 8;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_lng = this->_internal_lng();
  uint32_t raw_lng;
  memcpy(&raw_lng, &tmp_lng, sizeof(tmp_lng));
  if (raw_lng != 0) {
    total_size += 1 + 4;
  }

  // int64 updated_unix_millis = 11;
  if (this->_internal_updated_unix_millis() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_updated_unix_millis());
  }

  // float alt = 9;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_alt = this->_internal_alt();
  uint32_t raw_alt;
  memcpy(&raw_alt, &tmp_alt, sizeof(tmp_alt));
  if (raw_alt != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData FsNodeUpdate::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    FsNodeUpdate::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*FsNodeUpdate::GetClassData() const { return &_class_data_; }


void FsNodeUpdate::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<FsNodeUpdate*>(&to_msg);
  auto& from = static_cast<const FsNodeUpdate&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:yass.fs.FsNodeUpdate)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.network_params_.MergeFrom(from._impl_.network_params_);
  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_pos_str().empty()) {
    _this->_internal_set_pos_str(from._internal_pos_str());
  }
  if (from._internal_in_shadow() != 0) {
    _this->_internal_set_in_shadow(from._internal_in_shadow());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_x = from._internal_x();
  uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    _this->_internal_set_x(from._internal_x());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_y = from._internal_y();
  uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    _this->_internal_set_y(from._internal_y());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_z = from._internal_z();
  uint32_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    _this->_internal_set_z(from._internal_z());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_lat = from._internal_lat();
  uint32_t raw_lat;
  memcpy(&raw_lat, &tmp_lat, sizeof(tmp_lat));
  if (raw_lat != 0) {
    _this->_internal_set_lat(from._internal_lat());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_lng = from._internal_lng();
  uint32_t raw_lng;
  memcpy(&raw_lng, &tmp_lng, sizeof(tmp_lng));
  if (raw_lng != 0) {
    _this->_internal_set_lng(from._internal_lng());
  }
  if (from._internal_updated_unix_millis() != 0) {
    _this->_internal_set_updated_unix_millis(from._internal_updated_unix_millis());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_alt = from._internal_alt();
  uint32_t raw_alt;
  memcpy(&raw_alt, &tmp_alt, sizeof(tmp_alt));
  if (raw_alt != 0) {
    _this->_internal_set_alt(from._internal_alt());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void FsNodeUpdate::CopyFrom(const FsNodeUpdate& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yass.fs.FsNodeUpdate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FsNodeUpdate::IsInitialized() const {
  return true;
}

void FsNodeUpdate::InternalSwap(FsNodeUpdate* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.network_params_.InternalSwap(&other->_impl_.network_params_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.pos_str_, lhs_arena,
      &other->_impl_.pos_str_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FsNodeUpdate, _impl_.alt_)
      + sizeof(FsNodeUpdate::_impl_.alt_)
      - PROTOBUF_FIELD_OFFSET(FsNodeUpdate, _impl_.in_shadow_)>(
          reinterpret_cast<char*>(&_impl_.in_shadow_),
          reinterpret_cast<char*>(&other->_impl_.in_shadow_));
}

::PROTOBUF_NAMESPACE_ID::Metadata FsNodeUpdate::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_fs_5fnode_5fgeo_5fupdate_2eproto_getter, &descriptor_table_fs_5fnode_5fgeo_5fupdate_2eproto_once,
      file_level_metadata_fs_5fnode_5fgeo_5fupdate_2eproto[0]);
}

// ===================================================================

class FsNodeUpdateNetworkParamEntry::_Internal {
 public:
};

FsNodeUpdateNetworkParamEntry::FsNodeUpdateNetworkParamEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:yass.fs.FsNodeUpdateNetworkParamEntry)
}
FsNodeUpdateNetworkParamEntry::FsNodeUpdateNetworkParamEntry(const FsNodeUpdateNetworkParamEntry& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  FsNodeUpdateNetworkParamEntry* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.ip_){}
    , decltype(_impl_.subject_){}
    , decltype(_impl_.distance_){}
    , decltype(_impl_.package_delay_){}
    , decltype(_impl_.package_loss_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.ip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_ip().empty()) {
    _this->_impl_.ip_.Set(from._internal_ip(), 
      _this->GetArenaForAllocation());
  }
  _impl_.subject_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.subject_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_subject().empty()) {
    _this->_impl_.subject_.Set(from._internal_subject(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.distance_, &from._impl_.distance_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.package_loss_) -
    reinterpret_cast<char*>(&_impl_.distance_)) + sizeof(_impl_.package_loss_));
  // @@protoc_insertion_point(copy_constructor:yass.fs.FsNodeUpdateNetworkParamEntry)
}

inline void FsNodeUpdateNetworkParamEntry::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.ip_){}
    , decltype(_impl_.subject_){}
    , decltype(_impl_.distance_){0}
    , decltype(_impl_.package_delay_){0}
    , decltype(_impl_.package_loss_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.ip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.subject_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.subject_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

FsNodeUpdateNetworkParamEntry::~FsNodeUpdateNetworkParamEntry() {
  // @@protoc_insertion_point(destructor:yass.fs.FsNodeUpdateNetworkParamEntry)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void FsNodeUpdateNetworkParamEntry::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.ip_.Destroy();
  _impl_.subject_.Destroy();
}

void FsNodeUpdateNetworkParamEntry::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void FsNodeUpdateNetworkParamEntry::Clear() {
// @@protoc_insertion_point(message_clear_start:yass.fs.FsNodeUpdateNetworkParamEntry)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ip_.ClearToEmpty();
  _impl_.subject_.ClearToEmpty();
  ::memset(&_impl_.distance_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.package_loss_) -
      reinterpret_cast<char*>(&_impl_.distance_)) + sizeof(_impl_.package_loss_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FsNodeUpdateNetworkParamEntry::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string ip = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_ip();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "yass.fs.FsNodeUpdateNetworkParamEntry.ip"));
        } else
          goto handle_unusual;
        continue;
      // float distance = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _impl_.distance_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float package_delay = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 29)) {
          _impl_.package_delay_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float package_loss = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 37)) {
          _impl_.package_loss_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // string subject = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_subject();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "yass.fs.FsNodeUpdateNetworkParamEntry.subject"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* FsNodeUpdateNetworkParamEntry::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yass.fs.FsNodeUpdateNetworkParamEntry)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string ip = 1;
  if (!this->_internal_ip().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_ip().data(), static_cast<int>(this->_internal_ip().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yass.fs.FsNodeUpdateNetworkParamEntry.ip");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_ip(), target);
  }

  // float distance = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_distance = this->_internal_distance();
  uint32_t raw_distance;
  memcpy(&raw_distance, &tmp_distance, sizeof(tmp_distance));
  if (raw_distance != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_distance(), target);
  }

  // float package_delay = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_package_delay = this->_internal_package_delay();
  uint32_t raw_package_delay;
  memcpy(&raw_package_delay, &tmp_package_delay, sizeof(tmp_package_delay));
  if (raw_package_delay != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(3, this->_internal_package_delay(), target);
  }

  // float package_loss = 4;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_package_loss = this->_internal_package_loss();
  uint32_t raw_package_loss;
  memcpy(&raw_package_loss, &tmp_package_loss, sizeof(tmp_package_loss));
  if (raw_package_loss != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(4, this->_internal_package_loss(), target);
  }

  // string subject = 5;
  if (!this->_internal_subject().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_subject().data(), static_cast<int>(this->_internal_subject().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yass.fs.FsNodeUpdateNetworkParamEntry.subject");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_subject(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yass.fs.FsNodeUpdateNetworkParamEntry)
  return target;
}

size_t FsNodeUpdateNetworkParamEntry::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yass.fs.FsNodeUpdateNetworkParamEntry)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string ip = 1;
  if (!this->_internal_ip().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_ip());
  }

  // string subject = 5;
  if (!this->_internal_subject().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_subject());
  }

  // float distance = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_distance = this->_internal_distance();
  uint32_t raw_distance;
  memcpy(&raw_distance, &tmp_distance, sizeof(tmp_distance));
  if (raw_distance != 0) {
    total_size += 1 + 4;
  }

  // float package_delay = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_package_delay = this->_internal_package_delay();
  uint32_t raw_package_delay;
  memcpy(&raw_package_delay, &tmp_package_delay, sizeof(tmp_package_delay));
  if (raw_package_delay != 0) {
    total_size += 1 + 4;
  }

  // float package_loss = 4;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_package_loss = this->_internal_package_loss();
  uint32_t raw_package_loss;
  memcpy(&raw_package_loss, &tmp_package_loss, sizeof(tmp_package_loss));
  if (raw_package_loss != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData FsNodeUpdateNetworkParamEntry::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    FsNodeUpdateNetworkParamEntry::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*FsNodeUpdateNetworkParamEntry::GetClassData() const { return &_class_data_; }


void FsNodeUpdateNetworkParamEntry::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<FsNodeUpdateNetworkParamEntry*>(&to_msg);
  auto& from = static_cast<const FsNodeUpdateNetworkParamEntry&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:yass.fs.FsNodeUpdateNetworkParamEntry)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_ip().empty()) {
    _this->_internal_set_ip(from._internal_ip());
  }
  if (!from._internal_subject().empty()) {
    _this->_internal_set_subject(from._internal_subject());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_distance = from._internal_distance();
  uint32_t raw_distance;
  memcpy(&raw_distance, &tmp_distance, sizeof(tmp_distance));
  if (raw_distance != 0) {
    _this->_internal_set_distance(from._internal_distance());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_package_delay = from._internal_package_delay();
  uint32_t raw_package_delay;
  memcpy(&raw_package_delay, &tmp_package_delay, sizeof(tmp_package_delay));
  if (raw_package_delay != 0) {
    _this->_internal_set_package_delay(from._internal_package_delay());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_package_loss = from._internal_package_loss();
  uint32_t raw_package_loss;
  memcpy(&raw_package_loss, &tmp_package_loss, sizeof(tmp_package_loss));
  if (raw_package_loss != 0) {
    _this->_internal_set_package_loss(from._internal_package_loss());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void FsNodeUpdateNetworkParamEntry::CopyFrom(const FsNodeUpdateNetworkParamEntry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yass.fs.FsNodeUpdateNetworkParamEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FsNodeUpdateNetworkParamEntry::IsInitialized() const {
  return true;
}

void FsNodeUpdateNetworkParamEntry::InternalSwap(FsNodeUpdateNetworkParamEntry* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.ip_, lhs_arena,
      &other->_impl_.ip_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.subject_, lhs_arena,
      &other->_impl_.subject_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FsNodeUpdateNetworkParamEntry, _impl_.package_loss_)
      + sizeof(FsNodeUpdateNetworkParamEntry::_impl_.package_loss_)
      - PROTOBUF_FIELD_OFFSET(FsNodeUpdateNetworkParamEntry, _impl_.distance_)>(
          reinterpret_cast<char*>(&_impl_.distance_),
          reinterpret_cast<char*>(&other->_impl_.distance_));
}

::PROTOBUF_NAMESPACE_ID::Metadata FsNodeUpdateNetworkParamEntry::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_fs_5fnode_5fgeo_5fupdate_2eproto_getter, &descriptor_table_fs_5fnode_5fgeo_5fupdate_2eproto_once,
      file_level_metadata_fs_5fnode_5fgeo_5fupdate_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace fs
}  // namespace yass
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::yass::fs::FsNodeUpdate*
Arena::CreateMaybeMessage< ::yass::fs::FsNodeUpdate >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yass::fs::FsNodeUpdate >(arena);
}
template<> PROTOBUF_NOINLINE ::yass::fs::FsNodeUpdateNetworkParamEntry*
Arena::CreateMaybeMessage< ::yass::fs::FsNodeUpdateNetworkParamEntry >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yass::fs::FsNodeUpdateNetworkParamEntry >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
