// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geocalc_message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_geocalc_5fmessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_geocalc_5fmessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_geocalc_5fmessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_geocalc_5fmessage_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_geocalc_5fmessage_2eproto;
namespace yass {
namespace fs {
class Distance;
struct DistanceDefaultTypeInternal;
extern DistanceDefaultTypeInternal _Distance_default_instance_;
class GeoCommon;
struct GeoCommonDefaultTypeInternal;
extern GeoCommonDefaultTypeInternal _GeoCommon_default_instance_;
class Item;
struct ItemDefaultTypeInternal;
extern ItemDefaultTypeInternal _Item_default_instance_;
}  // namespace fs
}  // namespace yass
PROTOBUF_NAMESPACE_OPEN
template<> ::yass::fs::Distance* Arena::CreateMaybeMessage<::yass::fs::Distance>(Arena*);
template<> ::yass::fs::GeoCommon* Arena::CreateMaybeMessage<::yass::fs::GeoCommon>(Arena*);
template<> ::yass::fs::Item* Arena::CreateMaybeMessage<::yass::fs::Item>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace yass {
namespace fs {

// ===================================================================

class Item final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yass.fs.Item) */ {
 public:
  inline Item() : Item(nullptr) {}
  ~Item() override;
  explicit PROTOBUF_CONSTEXPR Item(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Item(const Item& from);
  Item(Item&& from) noexcept
    : Item() {
    *this = ::std::move(from);
  }

  inline Item& operator=(const Item& from) {
    CopyFrom(from);
    return *this;
  }
  inline Item& operator=(Item&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Item& default_instance() {
    return *internal_default_instance();
  }
  static inline const Item* internal_default_instance() {
    return reinterpret_cast<const Item*>(
               &_Item_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Item& a, Item& b) {
    a.Swap(&b);
  }
  inline void Swap(Item* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Item* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Item* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Item>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Item& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Item& from) {
    Item::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Item* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yass.fs.Item";
  }
  protected:
  explicit Item(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 2,
    kXFieldNumber = 3,
    kYFieldNumber = 4,
    kZFieldNumber = 5,
    kIdFieldNumber = 1,
    kInTheSunFieldNumber = 9,
    kLatFieldNumber = 6,
    kLonFieldNumber = 7,
    kAltFieldNumber = 8,
  };
  // string name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // double x = 3;
  void clear_x();
  double x() const;
  void set_x(double value);
  private:
  double _internal_x() const;
  void _internal_set_x(double value);
  public:

  // double y = 4;
  void clear_y();
  double y() const;
  void set_y(double value);
  private:
  double _internal_y() const;
  void _internal_set_y(double value);
  public:

  // double z = 5;
  void clear_z();
  double z() const;
  void set_z(double value);
  private:
  double _internal_z() const;
  void _internal_set_z(double value);
  public:

  // int32 id = 1;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // bool in_the_sun = 9;
  void clear_in_the_sun();
  bool in_the_sun() const;
  void set_in_the_sun(bool value);
  private:
  bool _internal_in_the_sun() const;
  void _internal_set_in_the_sun(bool value);
  public:

  // double lat = 6;
  void clear_lat();
  double lat() const;
  void set_lat(double value);
  private:
  double _internal_lat() const;
  void _internal_set_lat(double value);
  public:

  // double lon = 7;
  void clear_lon();
  double lon() const;
  void set_lon(double value);
  private:
  double _internal_lon() const;
  void _internal_set_lon(double value);
  public:

  // double alt = 8;
  void clear_alt();
  double alt() const;
  void set_alt(double value);
  private:
  double _internal_alt() const;
  void _internal_set_alt(double value);
  public:

  // @@protoc_insertion_point(class_scope:yass.fs.Item)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    double x_;
    double y_;
    double z_;
    int32_t id_;
    bool in_the_sun_;
    double lat_;
    double lon_;
    double alt_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_geocalc_5fmessage_2eproto;
};
// -------------------------------------------------------------------

class Distance final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yass.fs.Distance) */ {
 public:
  inline Distance() : Distance(nullptr) {}
  ~Distance() override;
  explicit PROTOBUF_CONSTEXPR Distance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Distance(const Distance& from);
  Distance(Distance&& from) noexcept
    : Distance() {
    *this = ::std::move(from);
  }

  inline Distance& operator=(const Distance& from) {
    CopyFrom(from);
    return *this;
  }
  inline Distance& operator=(Distance&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Distance& default_instance() {
    return *internal_default_instance();
  }
  static inline const Distance* internal_default_instance() {
    return reinterpret_cast<const Distance*>(
               &_Distance_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Distance& a, Distance& b) {
    a.Swap(&b);
  }
  inline void Swap(Distance* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Distance* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Distance* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Distance>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Distance& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Distance& from) {
    Distance::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Distance* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yass.fs.Distance";
  }
  protected:
  explicit Distance(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kItemIdAFieldNumber = 1,
    kItemIdBFieldNumber = 2,
    kDistanceFieldNumber = 3,
    kLosFieldNumber = 4,
  };
  // int32 item_id_a = 1;
  void clear_item_id_a();
  int32_t item_id_a() const;
  void set_item_id_a(int32_t value);
  private:
  int32_t _internal_item_id_a() const;
  void _internal_set_item_id_a(int32_t value);
  public:

  // int32 item_id_b = 2;
  void clear_item_id_b();
  int32_t item_id_b() const;
  void set_item_id_b(int32_t value);
  private:
  int32_t _internal_item_id_b() const;
  void _internal_set_item_id_b(int32_t value);
  public:

  // float distance = 3;
  void clear_distance();
  float distance() const;
  void set_distance(float value);
  private:
  float _internal_distance() const;
  void _internal_set_distance(float value);
  public:

  // bool los = 4;
  void clear_los();
  bool los() const;
  void set_los(bool value);
  private:
  bool _internal_los() const;
  void _internal_set_los(bool value);
  public:

  // @@protoc_insertion_point(class_scope:yass.fs.Distance)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t item_id_a_;
    int32_t item_id_b_;
    float distance_;
    bool los_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_geocalc_5fmessage_2eproto;
};
// -------------------------------------------------------------------

class GeoCommon final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yass.fs.GeoCommon) */ {
 public:
  inline GeoCommon() : GeoCommon(nullptr) {}
  ~GeoCommon() override;
  explicit PROTOBUF_CONSTEXPR GeoCommon(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GeoCommon(const GeoCommon& from);
  GeoCommon(GeoCommon&& from) noexcept
    : GeoCommon() {
    *this = ::std::move(from);
  }

  inline GeoCommon& operator=(const GeoCommon& from) {
    CopyFrom(from);
    return *this;
  }
  inline GeoCommon& operator=(GeoCommon&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GeoCommon& default_instance() {
    return *internal_default_instance();
  }
  static inline const GeoCommon* internal_default_instance() {
    return reinterpret_cast<const GeoCommon*>(
               &_GeoCommon_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GeoCommon& a, GeoCommon& b) {
    a.Swap(&b);
  }
  inline void Swap(GeoCommon* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GeoCommon* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GeoCommon* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GeoCommon>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GeoCommon& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GeoCommon& from) {
    GeoCommon::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GeoCommon* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yass.fs.GeoCommon";
  }
  protected:
  explicit GeoCommon(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kItemsFieldNumber = 2,
    kDistancesFieldNumber = 3,
    kTimeFieldNumber = 1,
  };
  // repeated .yass.fs.Item items = 2;
  int items_size() const;
  private:
  int _internal_items_size() const;
  public:
  void clear_items();
  ::yass::fs::Item* mutable_items(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::yass::fs::Item >*
      mutable_items();
  private:
  const ::yass::fs::Item& _internal_items(int index) const;
  ::yass::fs::Item* _internal_add_items();
  public:
  const ::yass::fs::Item& items(int index) const;
  ::yass::fs::Item* add_items();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::yass::fs::Item >&
      items() const;

  // repeated .yass.fs.Distance distances = 3;
  int distances_size() const;
  private:
  int _internal_distances_size() const;
  public:
  void clear_distances();
  ::yass::fs::Distance* mutable_distances(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::yass::fs::Distance >*
      mutable_distances();
  private:
  const ::yass::fs::Distance& _internal_distances(int index) const;
  ::yass::fs::Distance* _internal_add_distances();
  public:
  const ::yass::fs::Distance& distances(int index) const;
  ::yass::fs::Distance* add_distances();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::yass::fs::Distance >&
      distances() const;

  // .google.protobuf.Timestamp time = 1;
  bool has_time() const;
  private:
  bool _internal_has_time() const;
  public:
  void clear_time();
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& time() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Timestamp* release_time();
  ::PROTOBUF_NAMESPACE_ID::Timestamp* mutable_time();
  void set_allocated_time(::PROTOBUF_NAMESPACE_ID::Timestamp* time);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& _internal_time() const;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_time();
  public:
  void unsafe_arena_set_allocated_time(
      ::PROTOBUF_NAMESPACE_ID::Timestamp* time);
  ::PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_time();

  // @@protoc_insertion_point(class_scope:yass.fs.GeoCommon)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::yass::fs::Item > items_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::yass::fs::Distance > distances_;
    ::PROTOBUF_NAMESPACE_ID::Timestamp* time_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_geocalc_5fmessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Item

// int32 id = 1;
inline void Item::clear_id() {
  _impl_.id_ = 0;
}
inline int32_t Item::_internal_id() const {
  return _impl_.id_;
}
inline int32_t Item::id() const {
  // @@protoc_insertion_point(field_get:yass.fs.Item.id)
  return _internal_id();
}
inline void Item::_internal_set_id(int32_t value) {
  
  _impl_.id_ = value;
}
inline void Item::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:yass.fs.Item.id)
}

// string name = 2;
inline void Item::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& Item::name() const {
  // @@protoc_insertion_point(field_get:yass.fs.Item.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Item::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:yass.fs.Item.name)
}
inline std::string* Item::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:yass.fs.Item.name)
  return _s;
}
inline const std::string& Item::_internal_name() const {
  return _impl_.name_.Get();
}
inline void Item::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* Item::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* Item::release_name() {
  // @@protoc_insertion_point(field_release:yass.fs.Item.name)
  return _impl_.name_.Release();
}
inline void Item::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:yass.fs.Item.name)
}

// double x = 3;
inline void Item::clear_x() {
  _impl_.x_ = 0;
}
inline double Item::_internal_x() const {
  return _impl_.x_;
}
inline double Item::x() const {
  // @@protoc_insertion_point(field_get:yass.fs.Item.x)
  return _internal_x();
}
inline void Item::_internal_set_x(double value) {
  
  _impl_.x_ = value;
}
inline void Item::set_x(double value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:yass.fs.Item.x)
}

// double y = 4;
inline void Item::clear_y() {
  _impl_.y_ = 0;
}
inline double Item::_internal_y() const {
  return _impl_.y_;
}
inline double Item::y() const {
  // @@protoc_insertion_point(field_get:yass.fs.Item.y)
  return _internal_y();
}
inline void Item::_internal_set_y(double value) {
  
  _impl_.y_ = value;
}
inline void Item::set_y(double value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:yass.fs.Item.y)
}

// double z = 5;
inline void Item::clear_z() {
  _impl_.z_ = 0;
}
inline double Item::_internal_z() const {
  return _impl_.z_;
}
inline double Item::z() const {
  // @@protoc_insertion_point(field_get:yass.fs.Item.z)
  return _internal_z();
}
inline void Item::_internal_set_z(double value) {
  
  _impl_.z_ = value;
}
inline void Item::set_z(double value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:yass.fs.Item.z)
}

// double lat = 6;
inline void Item::clear_lat() {
  _impl_.lat_ = 0;
}
inline double Item::_internal_lat() const {
  return _impl_.lat_;
}
inline double Item::lat() const {
  // @@protoc_insertion_point(field_get:yass.fs.Item.lat)
  return _internal_lat();
}
inline void Item::_internal_set_lat(double value) {
  
  _impl_.lat_ = value;
}
inline void Item::set_lat(double value) {
  _internal_set_lat(value);
  // @@protoc_insertion_point(field_set:yass.fs.Item.lat)
}

// double lon = 7;
inline void Item::clear_lon() {
  _impl_.lon_ = 0;
}
inline double Item::_internal_lon() const {
  return _impl_.lon_;
}
inline double Item::lon() const {
  // @@protoc_insertion_point(field_get:yass.fs.Item.lon)
  return _internal_lon();
}
inline void Item::_internal_set_lon(double value) {
  
  _impl_.lon_ = value;
}
inline void Item::set_lon(double value) {
  _internal_set_lon(value);
  // @@protoc_insertion_point(field_set:yass.fs.Item.lon)
}

// double alt = 8;
inline void Item::clear_alt() {
  _impl_.alt_ = 0;
}
inline double Item::_internal_alt() const {
  return _impl_.alt_;
}
inline double Item::alt() const {
  // @@protoc_insertion_point(field_get:yass.fs.Item.alt)
  return _internal_alt();
}
inline void Item::_internal_set_alt(double value) {
  
  _impl_.alt_ = value;
}
inline void Item::set_alt(double value) {
  _internal_set_alt(value);
  // @@protoc_insertion_point(field_set:yass.fs.Item.alt)
}

// bool in_the_sun = 9;
inline void Item::clear_in_the_sun() {
  _impl_.in_the_sun_ = false;
}
inline bool Item::_internal_in_the_sun() const {
  return _impl_.in_the_sun_;
}
inline bool Item::in_the_sun() const {
  // @@protoc_insertion_point(field_get:yass.fs.Item.in_the_sun)
  return _internal_in_the_sun();
}
inline void Item::_internal_set_in_the_sun(bool value) {
  
  _impl_.in_the_sun_ = value;
}
inline void Item::set_in_the_sun(bool value) {
  _internal_set_in_the_sun(value);
  // @@protoc_insertion_point(field_set:yass.fs.Item.in_the_sun)
}

// -------------------------------------------------------------------

// Distance

// int32 item_id_a = 1;
inline void Distance::clear_item_id_a() {
  _impl_.item_id_a_ = 0;
}
inline int32_t Distance::_internal_item_id_a() const {
  return _impl_.item_id_a_;
}
inline int32_t Distance::item_id_a() const {
  // @@protoc_insertion_point(field_get:yass.fs.Distance.item_id_a)
  return _internal_item_id_a();
}
inline void Distance::_internal_set_item_id_a(int32_t value) {
  
  _impl_.item_id_a_ = value;
}
inline void Distance::set_item_id_a(int32_t value) {
  _internal_set_item_id_a(value);
  // @@protoc_insertion_point(field_set:yass.fs.Distance.item_id_a)
}

// int32 item_id_b = 2;
inline void Distance::clear_item_id_b() {
  _impl_.item_id_b_ = 0;
}
inline int32_t Distance::_internal_item_id_b() const {
  return _impl_.item_id_b_;
}
inline int32_t Distance::item_id_b() const {
  // @@protoc_insertion_point(field_get:yass.fs.Distance.item_id_b)
  return _internal_item_id_b();
}
inline void Distance::_internal_set_item_id_b(int32_t value) {
  
  _impl_.item_id_b_ = value;
}
inline void Distance::set_item_id_b(int32_t value) {
  _internal_set_item_id_b(value);
  // @@protoc_insertion_point(field_set:yass.fs.Distance.item_id_b)
}

// float distance = 3;
inline void Distance::clear_distance() {
  _impl_.distance_ = 0;
}
inline float Distance::_internal_distance() const {
  return _impl_.distance_;
}
inline float Distance::distance() const {
  // @@protoc_insertion_point(field_get:yass.fs.Distance.distance)
  return _internal_distance();
}
inline void Distance::_internal_set_distance(float value) {
  
  _impl_.distance_ = value;
}
inline void Distance::set_distance(float value) {
  _internal_set_distance(value);
  // @@protoc_insertion_point(field_set:yass.fs.Distance.distance)
}

// bool los = 4;
inline void Distance::clear_los() {
  _impl_.los_ = false;
}
inline bool Distance::_internal_los() const {
  return _impl_.los_;
}
inline bool Distance::los() const {
  // @@protoc_insertion_point(field_get:yass.fs.Distance.los)
  return _internal_los();
}
inline void Distance::_internal_set_los(bool value) {
  
  _impl_.los_ = value;
}
inline void Distance::set_los(bool value) {
  _internal_set_los(value);
  // @@protoc_insertion_point(field_set:yass.fs.Distance.los)
}

// -------------------------------------------------------------------

// GeoCommon

// .google.protobuf.Timestamp time = 1;
inline bool GeoCommon::_internal_has_time() const {
  return this != internal_default_instance() && _impl_.time_ != nullptr;
}
inline bool GeoCommon::has_time() const {
  return _internal_has_time();
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& GeoCommon::_internal_time() const {
  const ::PROTOBUF_NAMESPACE_ID::Timestamp* p = _impl_.time_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Timestamp&>(
      ::PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& GeoCommon::time() const {
  // @@protoc_insertion_point(field_get:yass.fs.GeoCommon.time)
  return _internal_time();
}
inline void GeoCommon::unsafe_arena_set_allocated_time(
    ::PROTOBUF_NAMESPACE_ID::Timestamp* time) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.time_);
  }
  _impl_.time_ = time;
  if (time) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:yass.fs.GeoCommon.time)
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* GeoCommon::release_time() {
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.time_;
  _impl_.time_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* GeoCommon::unsafe_arena_release_time() {
  // @@protoc_insertion_point(field_release:yass.fs.GeoCommon.time)
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.time_;
  _impl_.time_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* GeoCommon::_internal_mutable_time() {
  
  if (_impl_.time_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaForAllocation());
    _impl_.time_ = p;
  }
  return _impl_.time_;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* GeoCommon::mutable_time() {
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _msg = _internal_mutable_time();
  // @@protoc_insertion_point(field_mutable:yass.fs.GeoCommon.time)
  return _msg;
}
inline void GeoCommon::set_allocated_time(::PROTOBUF_NAMESPACE_ID::Timestamp* time) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.time_);
  }
  if (time) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(time));
    if (message_arena != submessage_arena) {
      time = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, time, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.time_ = time;
  // @@protoc_insertion_point(field_set_allocated:yass.fs.GeoCommon.time)
}

// repeated .yass.fs.Item items = 2;
inline int GeoCommon::_internal_items_size() const {
  return _impl_.items_.size();
}
inline int GeoCommon::items_size() const {
  return _internal_items_size();
}
inline void GeoCommon::clear_items() {
  _impl_.items_.Clear();
}
inline ::yass::fs::Item* GeoCommon::mutable_items(int index) {
  // @@protoc_insertion_point(field_mutable:yass.fs.GeoCommon.items)
  return _impl_.items_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::yass::fs::Item >*
GeoCommon::mutable_items() {
  // @@protoc_insertion_point(field_mutable_list:yass.fs.GeoCommon.items)
  return &_impl_.items_;
}
inline const ::yass::fs::Item& GeoCommon::_internal_items(int index) const {
  return _impl_.items_.Get(index);
}
inline const ::yass::fs::Item& GeoCommon::items(int index) const {
  // @@protoc_insertion_point(field_get:yass.fs.GeoCommon.items)
  return _internal_items(index);
}
inline ::yass::fs::Item* GeoCommon::_internal_add_items() {
  return _impl_.items_.Add();
}
inline ::yass::fs::Item* GeoCommon::add_items() {
  ::yass::fs::Item* _add = _internal_add_items();
  // @@protoc_insertion_point(field_add:yass.fs.GeoCommon.items)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::yass::fs::Item >&
GeoCommon::items() const {
  // @@protoc_insertion_point(field_list:yass.fs.GeoCommon.items)
  return _impl_.items_;
}

// repeated .yass.fs.Distance distances = 3;
inline int GeoCommon::_internal_distances_size() const {
  return _impl_.distances_.size();
}
inline int GeoCommon::distances_size() const {
  return _internal_distances_size();
}
inline void GeoCommon::clear_distances() {
  _impl_.distances_.Clear();
}
inline ::yass::fs::Distance* GeoCommon::mutable_distances(int index) {
  // @@protoc_insertion_point(field_mutable:yass.fs.GeoCommon.distances)
  return _impl_.distances_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::yass::fs::Distance >*
GeoCommon::mutable_distances() {
  // @@protoc_insertion_point(field_mutable_list:yass.fs.GeoCommon.distances)
  return &_impl_.distances_;
}
inline const ::yass::fs::Distance& GeoCommon::_internal_distances(int index) const {
  return _impl_.distances_.Get(index);
}
inline const ::yass::fs::Distance& GeoCommon::distances(int index) const {
  // @@protoc_insertion_point(field_get:yass.fs.GeoCommon.distances)
  return _internal_distances(index);
}
inline ::yass::fs::Distance* GeoCommon::_internal_add_distances() {
  return _impl_.distances_.Add();
}
inline ::yass::fs::Distance* GeoCommon::add_distances() {
  ::yass::fs::Distance* _add = _internal_add_distances();
  // @@protoc_insertion_point(field_add:yass.fs.GeoCommon.distances)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::yass::fs::Distance >&
GeoCommon::distances() const {
  // @@protoc_insertion_point(field_list:yass.fs.GeoCommon.distances)
  return _impl_.distances_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace fs
}  // namespace yass

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_geocalc_5fmessage_2eproto
