// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: time_update.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_time_5fupdate_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_time_5fupdate_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_time_5fupdate_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_time_5fupdate_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_time_5fupdate_2eproto;
namespace yass {
namespace fs {
class TimeUpdate;
struct TimeUpdateDefaultTypeInternal;
extern TimeUpdateDefaultTypeInternal _TimeUpdate_default_instance_;
}  // namespace fs
}  // namespace yass
PROTOBUF_NAMESPACE_OPEN
template<> ::yass::fs::TimeUpdate* Arena::CreateMaybeMessage<::yass::fs::TimeUpdate>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace yass {
namespace fs {

// ===================================================================

class TimeUpdate final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yass.fs.TimeUpdate) */ {
 public:
  inline TimeUpdate() : TimeUpdate(nullptr) {}
  ~TimeUpdate() override;
  explicit PROTOBUF_CONSTEXPR TimeUpdate(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TimeUpdate(const TimeUpdate& from);
  TimeUpdate(TimeUpdate&& from) noexcept
    : TimeUpdate() {
    *this = ::std::move(from);
  }

  inline TimeUpdate& operator=(const TimeUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  inline TimeUpdate& operator=(TimeUpdate&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TimeUpdate& default_instance() {
    return *internal_default_instance();
  }
  static inline const TimeUpdate* internal_default_instance() {
    return reinterpret_cast<const TimeUpdate*>(
               &_TimeUpdate_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TimeUpdate& a, TimeUpdate& b) {
    a.Swap(&b);
  }
  inline void Swap(TimeUpdate* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TimeUpdate* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TimeUpdate* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TimeUpdate>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TimeUpdate& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TimeUpdate& from) {
    TimeUpdate::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TimeUpdate* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yass.fs.TimeUpdate";
  }
  protected:
  explicit TimeUpdate(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNowFieldNumber = 2,
    kOngoingFieldNumber = 1,
  };
  // int64 now = 2;
  void clear_now();
  int64_t now() const;
  void set_now(int64_t value);
  private:
  int64_t _internal_now() const;
  void _internal_set_now(int64_t value);
  public:

  // bool ongoing = 1;
  void clear_ongoing();
  bool ongoing() const;
  void set_ongoing(bool value);
  private:
  bool _internal_ongoing() const;
  void _internal_set_ongoing(bool value);
  public:

  // @@protoc_insertion_point(class_scope:yass.fs.TimeUpdate)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t now_;
    bool ongoing_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_time_5fupdate_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TimeUpdate

// bool ongoing = 1;
inline void TimeUpdate::clear_ongoing() {
  _impl_.ongoing_ = false;
}
inline bool TimeUpdate::_internal_ongoing() const {
  return _impl_.ongoing_;
}
inline bool TimeUpdate::ongoing() const {
  // @@protoc_insertion_point(field_get:yass.fs.TimeUpdate.ongoing)
  return _internal_ongoing();
}
inline void TimeUpdate::_internal_set_ongoing(bool value) {
  
  _impl_.ongoing_ = value;
}
inline void TimeUpdate::set_ongoing(bool value) {
  _internal_set_ongoing(value);
  // @@protoc_insertion_point(field_set:yass.fs.TimeUpdate.ongoing)
}

// int64 now = 2;
inline void TimeUpdate::clear_now() {
  _impl_.now_ = int64_t{0};
}
inline int64_t TimeUpdate::_internal_now() const {
  return _impl_.now_;
}
inline int64_t TimeUpdate::now() const {
  // @@protoc_insertion_point(field_get:yass.fs.TimeUpdate.now)
  return _internal_now();
}
inline void TimeUpdate::_internal_set_now(int64_t value) {
  
  _impl_.now_ = value;
}
inline void TimeUpdate::set_now(int64_t value) {
  _internal_set_now(value);
  // @@protoc_insertion_point(field_set:yass.fs.TimeUpdate.now)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace fs
}  // namespace yass

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_time_5fupdate_2eproto
