// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: time_update.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimeUpdate struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Ongoing bool                   `protobuf:"varint,1,opt,name=ongoing,proto3" json:"ongoing,omitempty"`
	// Now timestamp as Unix milliseconds.
	Now           int64 `protobuf:"varint,2,opt,name=now,proto3" json:"now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeUpdate) Reset() {
	*x = TimeUpdate{}
	mi := &file_time_update_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeUpdate) ProtoMessage() {}

func (x *TimeUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_time_update_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeUpdate.ProtoReflect.Descriptor instead.
func (*TimeUpdate) Descriptor() ([]byte, []int) {
	return file_time_update_proto_rawDescGZIP(), []int{0}
}

func (x *TimeUpdate) GetOngoing() bool {
	if x != nil {
		return x.Ongoing
	}
	return false
}

func (x *TimeUpdate) GetNow() int64 {
	if x != nil {
		return x.Now
	}
	return 0
}

var File_time_update_proto protoreflect.FileDescriptor

var file_time_update_proto_rawDesc = string([]byte{
	0x0a, 0x11, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x79, 0x61, 0x73, 0x73, 0x2e, 0x66, 0x73, 0x22, 0x38, 0x0a, 0x0a,
	0x54, 0x69, 0x6d, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x6e,
	0x67, 0x6f, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x6f, 0x6e, 0x67,
	0x6f, 0x69, 0x6e, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x6e, 0x6f, 0x77, 0x42, 0x43, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x75, 0x6f, 0x62, 0x69, 0x74, 0x78, 0x2f, 0x79, 0x61, 0x73,
	0x73, 0x2d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2d, 0x63, 0x6f, 0x6d, 0x70, 0x6f,
	0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x67, 0x6f, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_time_update_proto_rawDescOnce sync.Once
	file_time_update_proto_rawDescData []byte
)

func file_time_update_proto_rawDescGZIP() []byte {
	file_time_update_proto_rawDescOnce.Do(func() {
		file_time_update_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_time_update_proto_rawDesc), len(file_time_update_proto_rawDesc)))
	})
	return file_time_update_proto_rawDescData
}

var file_time_update_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_time_update_proto_goTypes = []any{
	(*TimeUpdate)(nil), // 0: yass.fs.TimeUpdate
}
var file_time_update_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_time_update_proto_init() }
func file_time_update_proto_init() {
	if File_time_update_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_time_update_proto_rawDesc), len(file_time_update_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_time_update_proto_goTypes,
		DependencyIndexes: file_time_update_proto_depIdxs,
		MessageInfos:      file_time_update_proto_msgTypes,
	}.Build()
	File_time_update_proto = out.File
	file_time_update_proto_goTypes = nil
	file_time_update_proto_depIdxs = nil
}
