# This rule is not used by the project x itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to yass.int.esa.yass resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: x
    app.kubernetes.io/managed-by: kustomize
  name: sat-viewer-role
rules:
- apiGroups:
  - yass.int.esa.yass
  resources:
  - sats
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - yass.int.esa.yass
  resources:
  - sats/status
  verbs:
  - get
