// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: proto/agend_exp_end_request.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_EXPERIMENT_END_REQUEST_SUCCESS Status = 0
	Status_EXPERIMENT_END_REQUEST_FAILURE Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "EXPERIMENT_END_REQUEST_SUCCESS",
		1: "EXPERIMENT_END_REQUEST_FAILURE",
	}
	Status_value = map[string]int32{
		"EXPERIMENT_END_REQUEST_SUCCESS": 0,
		"EXPERIMENT_END_REQUEST_FAILURE": 1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agend_exp_end_request_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_proto_agend_exp_end_request_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_agend_exp_end_request_proto_rawDescGZIP(), []int{0}
}

type AgentExperimentEndRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=yass.fs.Status" json:"status,omitempty"`
	Comment       string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentExperimentEndRequest) Reset() {
	*x = AgentExperimentEndRequest{}
	mi := &file_proto_agend_exp_end_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentExperimentEndRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentExperimentEndRequest) ProtoMessage() {}

func (x *AgentExperimentEndRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agend_exp_end_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentExperimentEndRequest.ProtoReflect.Descriptor instead.
func (*AgentExperimentEndRequest) Descriptor() ([]byte, []int) {
	return file_proto_agend_exp_end_request_proto_rawDescGZIP(), []int{0}
}

func (x *AgentExperimentEndRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_EXPERIMENT_END_REQUEST_SUCCESS
}

func (x *AgentExperimentEndRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

var File_proto_agend_exp_end_request_proto protoreflect.FileDescriptor

var file_proto_agend_exp_end_request_proto_rawDesc = string([]byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x64, 0x5f, 0x65, 0x78,
	0x70, 0x5f, 0x65, 0x6e, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x79, 0x61, 0x73, 0x73, 0x2e, 0x66, 0x73, 0x22, 0x5e, 0x0a, 0x19,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x45, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x45,
	0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x79, 0x61, 0x73, 0x73,
	0x2e, 0x66, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2a, 0x50, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x1e, 0x45, 0x58, 0x50, 0x45, 0x52, 0x49,
	0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x45, 0x4e, 0x44, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54,
	0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x22, 0x0a, 0x1e, 0x45, 0x58,
	0x50, 0x45, 0x52, 0x49, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x45, 0x4e, 0x44, 0x5f, 0x52, 0x45, 0x51,
	0x55, 0x45, 0x53, 0x54, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x55, 0x52, 0x45, 0x10, 0x01, 0x42, 0x43,
	0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x75, 0x6f,
	0x62, 0x69, 0x74, 0x78, 0x2f, 0x79, 0x61, 0x73, 0x73, 0x2d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2d, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x67, 0x6f,
	0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_agend_exp_end_request_proto_rawDescOnce sync.Once
	file_proto_agend_exp_end_request_proto_rawDescData []byte
)

func file_proto_agend_exp_end_request_proto_rawDescGZIP() []byte {
	file_proto_agend_exp_end_request_proto_rawDescOnce.Do(func() {
		file_proto_agend_exp_end_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agend_exp_end_request_proto_rawDesc), len(file_proto_agend_exp_end_request_proto_rawDesc)))
	})
	return file_proto_agend_exp_end_request_proto_rawDescData
}

var file_proto_agend_exp_end_request_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_agend_exp_end_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_agend_exp_end_request_proto_goTypes = []any{
	(Status)(0),                       // 0: yass.fs.Status
	(*AgentExperimentEndRequest)(nil), // 1: yass.fs.AgentExperimentEndRequest
}
var file_proto_agend_exp_end_request_proto_depIdxs = []int32{
	0, // 0: yass.fs.AgentExperimentEndRequest.status:type_name -> yass.fs.Status
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_agend_exp_end_request_proto_init() }
func file_proto_agend_exp_end_request_proto_init() {
	if File_proto_agend_exp_end_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agend_exp_end_request_proto_rawDesc), len(file_proto_agend_exp_end_request_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_agend_exp_end_request_proto_goTypes,
		DependencyIndexes: file_proto_agend_exp_end_request_proto_depIdxs,
		EnumInfos:         file_proto_agend_exp_end_request_proto_enumTypes,
		MessageInfos:      file_proto_agend_exp_end_request_proto_msgTypes,
	}.Build()
	File_proto_agend_exp_end_request_proto = out.File
	file_proto_agend_exp_end_request_proto_goTypes = nil
	file_proto_agend_exp_end_request_proto_depIdxs = nil
}
