// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: proto/fs_node_update.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FsNodeUpdate struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InShadow bool                   `protobuf:"varint,2,opt,name=in_shadow,json=inShadow,proto3" json:"in_shadow,omitempty"`
	PosStr   *string                `protobuf:"bytes,3,opt,name=pos_str,json=posStr,proto3,oneof" json:"pos_str,omitempty"`
	// Last update timestamp as Unix seconds.
	UpdatedUnixSec int64 `protobuf:"varint,6,opt,name=updated_unix_sec,json=updatedUnixSec,proto3" json:"updated_unix_sec,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FsNodeUpdate) Reset() {
	*x = FsNodeUpdate{}
	mi := &file_proto_fs_node_update_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsNodeUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsNodeUpdate) ProtoMessage() {}

func (x *FsNodeUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fs_node_update_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsNodeUpdate.ProtoReflect.Descriptor instead.
func (*FsNodeUpdate) Descriptor() ([]byte, []int) {
	return file_proto_fs_node_update_proto_rawDescGZIP(), []int{0}
}

func (x *FsNodeUpdate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FsNodeUpdate) GetInShadow() bool {
	if x != nil {
		return x.InShadow
	}
	return false
}

func (x *FsNodeUpdate) GetPosStr() string {
	if x != nil && x.PosStr != nil {
		return *x.PosStr
	}
	return ""
}

func (x *FsNodeUpdate) GetUpdatedUnixSec() int64 {
	if x != nil {
		return x.UpdatedUnixSec
	}
	return 0
}

var File_proto_fs_node_update_proto protoreflect.FileDescriptor

var file_proto_fs_node_update_proto_rawDesc = string([]byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x73, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x79, 0x61,
	0x73, 0x73, 0x2e, 0x66, 0x73, 0x22, 0x8f, 0x01, 0x0a, 0x0c, 0x46, 0x73, 0x4e, 0x6f, 0x64, 0x65,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6e, 0x5f, 0x73, 0x68, 0x61,
	0x64, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x6e, 0x53, 0x68, 0x61,
	0x64, 0x6f, 0x77, 0x12, 0x1c, 0x0a, 0x07, 0x70, 0x6f, 0x73, 0x5f, 0x73, 0x74, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x53, 0x74, 0x72, 0x88, 0x01,
	0x01, 0x12, 0x28, 0x0a, 0x10, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x75, 0x6e, 0x69,
	0x78, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x55, 0x6e, 0x69, 0x78, 0x53, 0x65, 0x63, 0x42, 0x0a, 0x0a, 0x08, 0x5f,
	0x70, 0x6f, 0x73, 0x5f, 0x73, 0x74, 0x72, 0x42, 0x46, 0x5a, 0x44, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x45, 0x53, 0x41, 0x2d, 0x50, 0x68, 0x69, 0x4c, 0x61, 0x62,
	0x2f, 0x79, 0x61, 0x73, 0x73, 0x2d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2d, 0x63,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x67, 0x6f, 0x2d, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_fs_node_update_proto_rawDescOnce sync.Once
	file_proto_fs_node_update_proto_rawDescData []byte
)

func file_proto_fs_node_update_proto_rawDescGZIP() []byte {
	file_proto_fs_node_update_proto_rawDescOnce.Do(func() {
		file_proto_fs_node_update_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fs_node_update_proto_rawDesc), len(file_proto_fs_node_update_proto_rawDesc)))
	})
	return file_proto_fs_node_update_proto_rawDescData
}

var file_proto_fs_node_update_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_fs_node_update_proto_goTypes = []any{
	(*FsNodeUpdate)(nil), // 0: yass.fs.FsNodeUpdate
}
var file_proto_fs_node_update_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_fs_node_update_proto_init() }
func file_proto_fs_node_update_proto_init() {
	if File_proto_fs_node_update_proto != nil {
		return
	}
	file_proto_fs_node_update_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fs_node_update_proto_rawDesc), len(file_proto_fs_node_update_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_fs_node_update_proto_goTypes,
		DependencyIndexes: file_proto_fs_node_update_proto_depIdxs,
		MessageInfos:      file_proto_fs_node_update_proto_msgTypes,
	}.Build()
	File_proto_fs_node_update_proto = out.File
	file_proto_fs_node_update_proto_goTypes = nil
	file_proto_fs_node_update_proto_depIdxs = nil
}
