// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/fs_node_online_state.proto

#include "proto/fs_node_online_state.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace yass {
namespace fs {
PROTOBUF_CONSTEXPR FsNodeId::FsNodeId(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.experiment_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct FsNodeIdDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FsNodeIdDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FsNodeIdDefaultTypeInternal() {}
  union {
    FsNodeId _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FsNodeIdDefaultTypeInternal _FsNodeId_default_instance_;
PROTOBUF_CONSTEXPR FsNodeOnlineState::FsNodeOnlineState(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.ip_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.fsnodeid_)*/nullptr
  , /*decltype(_impl_.online_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct FsNodeOnlineStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FsNodeOnlineStateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FsNodeOnlineStateDefaultTypeInternal() {}
  union {
    FsNodeOnlineState _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FsNodeOnlineStateDefaultTypeInternal _FsNodeOnlineState_default_instance_;
}  // namespace fs
}  // namespace yass
static ::_pb::Metadata file_level_metadata_proto_2ffs_5fnode_5fonline_5fstate_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_proto_2ffs_5fnode_5fonline_5fstate_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_proto_2ffs_5fnode_5fonline_5fstate_2eproto = nullptr;

const uint32_t TableStruct_proto_2ffs_5fnode_5fonline_5fstate_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yass::fs::FsNodeId, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yass::fs::FsNodeId, _impl_.name_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::FsNodeId, _impl_.experiment_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yass::fs::FsNodeOnlineState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yass::fs::FsNodeOnlineState, _impl_.fsnodeid_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::FsNodeOnlineState, _impl_.ip_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::FsNodeOnlineState, _impl_.online_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::yass::fs::FsNodeId)},
  { 8, -1, -1, sizeof(::yass::fs::FsNodeOnlineState)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::yass::fs::_FsNodeId_default_instance_._instance,
  &::yass::fs::_FsNodeOnlineState_default_instance_._instance,
};

const char descriptor_table_protodef_proto_2ffs_5fnode_5fonline_5fstate_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n proto/fs_node_online_state.proto\022\007yass"
  ".fs\",\n\010FsNodeId\022\014\n\004name\030\001 \001(\t\022\022\n\nexperim"
  "ent\030\002 \001(\t\"T\n\021FsNodeOnlineState\022#\n\010fsNode"
  "Id\030\001 \001(\0132\021.yass.fs.FsNodeId\022\n\n\002ip\030\002 \001(\t\022"
  "\016\n\006online\030\003 \001(\010BCZAgithub.com/duobitx/ya"
  "ss-internal-components/go-common/proto;p"
  "rotob\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_proto_2ffs_5fnode_5fonline_5fstate_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_proto_2ffs_5fnode_5fonline_5fstate_2eproto = {
    false, false, 252, descriptor_table_protodef_proto_2ffs_5fnode_5fonline_5fstate_2eproto,
    "proto/fs_node_online_state.proto",
    &descriptor_table_proto_2ffs_5fnode_5fonline_5fstate_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_proto_2ffs_5fnode_5fonline_5fstate_2eproto::offsets,
    file_level_metadata_proto_2ffs_5fnode_5fonline_5fstate_2eproto, file_level_enum_descriptors_proto_2ffs_5fnode_5fonline_5fstate_2eproto,
    file_level_service_descriptors_proto_2ffs_5fnode_5fonline_5fstate_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_proto_2ffs_5fnode_5fonline_5fstate_2eproto_getter() {
  return &descriptor_table_proto_2ffs_5fnode_5fonline_5fstate_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_proto_2ffs_5fnode_5fonline_5fstate_2eproto(&descriptor_table_proto_2ffs_5fnode_5fonline_5fstate_2eproto);
namespace yass {
namespace fs {

// ===================================================================

class FsNodeId::_Internal {
 public:
};

FsNodeId::FsNodeId(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:yass.fs.FsNodeId)
}
FsNodeId::FsNodeId(const FsNodeId& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  FsNodeId* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.experiment_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.experiment_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.experiment_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_experiment().empty()) {
    _this->_impl_.experiment_.Set(from._internal_experiment(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:yass.fs.FsNodeId)
}

inline void FsNodeId::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.experiment_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.experiment_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.experiment_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

FsNodeId::~FsNodeId() {
  // @@protoc_insertion_point(destructor:yass.fs.FsNodeId)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void FsNodeId::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.name_.Destroy();
  _impl_.experiment_.Destroy();
}

void FsNodeId::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void FsNodeId::Clear() {
// @@protoc_insertion_point(message_clear_start:yass.fs.FsNodeId)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.experiment_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FsNodeId::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "yass.fs.FsNodeId.name"));
        } else
          goto handle_unusual;
        continue;
      // string experiment = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_experiment();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "yass.fs.FsNodeId.experiment"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* FsNodeId::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yass.fs.FsNodeId)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yass.fs.FsNodeId.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // string experiment = 2;
  if (!this->_internal_experiment().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_experiment().data(), static_cast<int>(this->_internal_experiment().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yass.fs.FsNodeId.experiment");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_experiment(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yass.fs.FsNodeId)
  return target;
}

size_t FsNodeId::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yass.fs.FsNodeId)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // string experiment = 2;
  if (!this->_internal_experiment().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_experiment());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData FsNodeId::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    FsNodeId::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*FsNodeId::GetClassData() const { return &_class_data_; }


void FsNodeId::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<FsNodeId*>(&to_msg);
  auto& from = static_cast<const FsNodeId&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:yass.fs.FsNodeId)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_experiment().empty()) {
    _this->_internal_set_experiment(from._internal_experiment());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void FsNodeId::CopyFrom(const FsNodeId& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yass.fs.FsNodeId)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FsNodeId::IsInitialized() const {
  return true;
}

void FsNodeId::InternalSwap(FsNodeId* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.experiment_, lhs_arena,
      &other->_impl_.experiment_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata FsNodeId::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2ffs_5fnode_5fonline_5fstate_2eproto_getter, &descriptor_table_proto_2ffs_5fnode_5fonline_5fstate_2eproto_once,
      file_level_metadata_proto_2ffs_5fnode_5fonline_5fstate_2eproto[0]);
}

// ===================================================================

class FsNodeOnlineState::_Internal {
 public:
  static const ::yass::fs::FsNodeId& fsnodeid(const FsNodeOnlineState* msg);
};

const ::yass::fs::FsNodeId&
FsNodeOnlineState::_Internal::fsnodeid(const FsNodeOnlineState* msg) {
  return *msg->_impl_.fsnodeid_;
}
FsNodeOnlineState::FsNodeOnlineState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:yass.fs.FsNodeOnlineState)
}
FsNodeOnlineState::FsNodeOnlineState(const FsNodeOnlineState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  FsNodeOnlineState* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.ip_){}
    , decltype(_impl_.fsnodeid_){nullptr}
    , decltype(_impl_.online_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.ip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_ip().empty()) {
    _this->_impl_.ip_.Set(from._internal_ip(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_fsnodeid()) {
    _this->_impl_.fsnodeid_ = new ::yass::fs::FsNodeId(*from._impl_.fsnodeid_);
  }
  _this->_impl_.online_ = from._impl_.online_;
  // @@protoc_insertion_point(copy_constructor:yass.fs.FsNodeOnlineState)
}

inline void FsNodeOnlineState::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.ip_){}
    , decltype(_impl_.fsnodeid_){nullptr}
    , decltype(_impl_.online_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.ip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

FsNodeOnlineState::~FsNodeOnlineState() {
  // @@protoc_insertion_point(destructor:yass.fs.FsNodeOnlineState)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void FsNodeOnlineState::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.ip_.Destroy();
  if (this != internal_default_instance()) delete _impl_.fsnodeid_;
}

void FsNodeOnlineState::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void FsNodeOnlineState::Clear() {
// @@protoc_insertion_point(message_clear_start:yass.fs.FsNodeOnlineState)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ip_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.fsnodeid_ != nullptr) {
    delete _impl_.fsnodeid_;
  }
  _impl_.fsnodeid_ = nullptr;
  _impl_.online_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FsNodeOnlineState::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .yass.fs.FsNodeId fsNodeId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_fsnodeid(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string ip = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_ip();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "yass.fs.FsNodeOnlineState.ip"));
        } else
          goto handle_unusual;
        continue;
      // bool online = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.online_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* FsNodeOnlineState::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yass.fs.FsNodeOnlineState)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .yass.fs.FsNodeId fsNodeId = 1;
  if (this->_internal_has_fsnodeid()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::fsnodeid(this),
        _Internal::fsnodeid(this).GetCachedSize(), target, stream);
  }

  // string ip = 2;
  if (!this->_internal_ip().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_ip().data(), static_cast<int>(this->_internal_ip().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yass.fs.FsNodeOnlineState.ip");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_ip(), target);
  }

  // bool online = 3;
  if (this->_internal_online() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_online(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yass.fs.FsNodeOnlineState)
  return target;
}

size_t FsNodeOnlineState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yass.fs.FsNodeOnlineState)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string ip = 2;
  if (!this->_internal_ip().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_ip());
  }

  // .yass.fs.FsNodeId fsNodeId = 1;
  if (this->_internal_has_fsnodeid()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.fsnodeid_);
  }

  // bool online = 3;
  if (this->_internal_online() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData FsNodeOnlineState::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    FsNodeOnlineState::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*FsNodeOnlineState::GetClassData() const { return &_class_data_; }


void FsNodeOnlineState::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<FsNodeOnlineState*>(&to_msg);
  auto& from = static_cast<const FsNodeOnlineState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:yass.fs.FsNodeOnlineState)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_ip().empty()) {
    _this->_internal_set_ip(from._internal_ip());
  }
  if (from._internal_has_fsnodeid()) {
    _this->_internal_mutable_fsnodeid()->::yass::fs::FsNodeId::MergeFrom(
        from._internal_fsnodeid());
  }
  if (from._internal_online() != 0) {
    _this->_internal_set_online(from._internal_online());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void FsNodeOnlineState::CopyFrom(const FsNodeOnlineState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yass.fs.FsNodeOnlineState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FsNodeOnlineState::IsInitialized() const {
  return true;
}

void FsNodeOnlineState::InternalSwap(FsNodeOnlineState* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.ip_, lhs_arena,
      &other->_impl_.ip_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FsNodeOnlineState, _impl_.online_)
      + sizeof(FsNodeOnlineState::_impl_.online_)
      - PROTOBUF_FIELD_OFFSET(FsNodeOnlineState, _impl_.fsnodeid_)>(
          reinterpret_cast<char*>(&_impl_.fsnodeid_),
          reinterpret_cast<char*>(&other->_impl_.fsnodeid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata FsNodeOnlineState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2ffs_5fnode_5fonline_5fstate_2eproto_getter, &descriptor_table_proto_2ffs_5fnode_5fonline_5fstate_2eproto_once,
      file_level_metadata_proto_2ffs_5fnode_5fonline_5fstate_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace fs
}  // namespace yass
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::yass::fs::FsNodeId*
Arena::CreateMaybeMessage< ::yass::fs::FsNodeId >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yass::fs::FsNodeId >(arena);
}
template<> PROTOBUF_NOINLINE ::yass::fs::FsNodeOnlineState*
Arena::CreateMaybeMessage< ::yass::fs::FsNodeOnlineState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yass::fs::FsNodeOnlineState >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
