// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/fs_node_geo_update.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_2ffs_5fnode_5fgeo_5fupdate_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_proto_2ffs_5fnode_5fgeo_5fupdate_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proto_2ffs_5fnode_5fgeo_5fupdate_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2ffs_5fnode_5fgeo_5fupdate_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2ffs_5fnode_5fgeo_5fupdate_2eproto;
namespace yass {
namespace fs {
class FsNodeUpdate;
struct FsNodeUpdateDefaultTypeInternal;
extern FsNodeUpdateDefaultTypeInternal _FsNodeUpdate_default_instance_;
class FsNodeUpdateNetworkParamEntry;
struct FsNodeUpdateNetworkParamEntryDefaultTypeInternal;
extern FsNodeUpdateNetworkParamEntryDefaultTypeInternal _FsNodeUpdateNetworkParamEntry_default_instance_;
}  // namespace fs
}  // namespace yass
PROTOBUF_NAMESPACE_OPEN
template<> ::yass::fs::FsNodeUpdate* Arena::CreateMaybeMessage<::yass::fs::FsNodeUpdate>(Arena*);
template<> ::yass::fs::FsNodeUpdateNetworkParamEntry* Arena::CreateMaybeMessage<::yass::fs::FsNodeUpdateNetworkParamEntry>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace yass {
namespace fs {

// ===================================================================

class FsNodeUpdate final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yass.fs.FsNodeUpdate) */ {
 public:
  inline FsNodeUpdate() : FsNodeUpdate(nullptr) {}
  ~FsNodeUpdate() override;
  explicit PROTOBUF_CONSTEXPR FsNodeUpdate(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FsNodeUpdate(const FsNodeUpdate& from);
  FsNodeUpdate(FsNodeUpdate&& from) noexcept
    : FsNodeUpdate() {
    *this = ::std::move(from);
  }

  inline FsNodeUpdate& operator=(const FsNodeUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  inline FsNodeUpdate& operator=(FsNodeUpdate&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FsNodeUpdate& default_instance() {
    return *internal_default_instance();
  }
  static inline const FsNodeUpdate* internal_default_instance() {
    return reinterpret_cast<const FsNodeUpdate*>(
               &_FsNodeUpdate_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FsNodeUpdate& a, FsNodeUpdate& b) {
    a.Swap(&b);
  }
  inline void Swap(FsNodeUpdate* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FsNodeUpdate* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FsNodeUpdate* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FsNodeUpdate>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FsNodeUpdate& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FsNodeUpdate& from) {
    FsNodeUpdate::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FsNodeUpdate* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yass.fs.FsNodeUpdate";
  }
  protected:
  explicit FsNodeUpdate(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNetworkParamsFieldNumber = 10,
    kNameFieldNumber = 1,
    kPosStrFieldNumber = 3,
    kInShadowFieldNumber = 2,
    kXFieldNumber = 4,
    kYFieldNumber = 5,
    kZFieldNumber = 6,
    kLatFieldNumber = 7,
    kLngFieldNumber = 8,
    kUpdatedUnixMillisFieldNumber = 11,
    kAltFieldNumber = 9,
  };
  // repeated .yass.fs.FsNodeUpdateNetworkParamEntry network_params = 10;
  int network_params_size() const;
  private:
  int _internal_network_params_size() const;
  public:
  void clear_network_params();
  ::yass::fs::FsNodeUpdateNetworkParamEntry* mutable_network_params(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::yass::fs::FsNodeUpdateNetworkParamEntry >*
      mutable_network_params();
  private:
  const ::yass::fs::FsNodeUpdateNetworkParamEntry& _internal_network_params(int index) const;
  ::yass::fs::FsNodeUpdateNetworkParamEntry* _internal_add_network_params();
  public:
  const ::yass::fs::FsNodeUpdateNetworkParamEntry& network_params(int index) const;
  ::yass::fs::FsNodeUpdateNetworkParamEntry* add_network_params();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::yass::fs::FsNodeUpdateNetworkParamEntry >&
      network_params() const;

  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string pos_str = 3;
  void clear_pos_str();
  const std::string& pos_str() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_pos_str(ArgT0&& arg0, ArgT... args);
  std::string* mutable_pos_str();
  PROTOBUF_NODISCARD std::string* release_pos_str();
  void set_allocated_pos_str(std::string* pos_str);
  private:
  const std::string& _internal_pos_str() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pos_str(const std::string& value);
  std::string* _internal_mutable_pos_str();
  public:

  // bool in_shadow = 2;
  void clear_in_shadow();
  bool in_shadow() const;
  void set_in_shadow(bool value);
  private:
  bool _internal_in_shadow() const;
  void _internal_set_in_shadow(bool value);
  public:

  // float x = 4;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 5;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 6;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // float lat = 7;
  void clear_lat();
  float lat() const;
  void set_lat(float value);
  private:
  float _internal_lat() const;
  void _internal_set_lat(float value);
  public:

  // float lng = 8;
  void clear_lng();
  float lng() const;
  void set_lng(float value);
  private:
  float _internal_lng() const;
  void _internal_set_lng(float value);
  public:

  // int64 updated_unix_millis = 11;
  void clear_updated_unix_millis();
  int64_t updated_unix_millis() const;
  void set_updated_unix_millis(int64_t value);
  private:
  int64_t _internal_updated_unix_millis() const;
  void _internal_set_updated_unix_millis(int64_t value);
  public:

  // float alt = 9;
  void clear_alt();
  float alt() const;
  void set_alt(float value);
  private:
  float _internal_alt() const;
  void _internal_set_alt(float value);
  public:

  // @@protoc_insertion_point(class_scope:yass.fs.FsNodeUpdate)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::yass::fs::FsNodeUpdateNetworkParamEntry > network_params_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr pos_str_;
    bool in_shadow_;
    float x_;
    float y_;
    float z_;
    float lat_;
    float lng_;
    int64_t updated_unix_millis_;
    float alt_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2ffs_5fnode_5fgeo_5fupdate_2eproto;
};
// -------------------------------------------------------------------

class FsNodeUpdateNetworkParamEntry final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yass.fs.FsNodeUpdateNetworkParamEntry) */ {
 public:
  inline FsNodeUpdateNetworkParamEntry() : FsNodeUpdateNetworkParamEntry(nullptr) {}
  ~FsNodeUpdateNetworkParamEntry() override;
  explicit PROTOBUF_CONSTEXPR FsNodeUpdateNetworkParamEntry(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FsNodeUpdateNetworkParamEntry(const FsNodeUpdateNetworkParamEntry& from);
  FsNodeUpdateNetworkParamEntry(FsNodeUpdateNetworkParamEntry&& from) noexcept
    : FsNodeUpdateNetworkParamEntry() {
    *this = ::std::move(from);
  }

  inline FsNodeUpdateNetworkParamEntry& operator=(const FsNodeUpdateNetworkParamEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline FsNodeUpdateNetworkParamEntry& operator=(FsNodeUpdateNetworkParamEntry&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FsNodeUpdateNetworkParamEntry& default_instance() {
    return *internal_default_instance();
  }
  static inline const FsNodeUpdateNetworkParamEntry* internal_default_instance() {
    return reinterpret_cast<const FsNodeUpdateNetworkParamEntry*>(
               &_FsNodeUpdateNetworkParamEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(FsNodeUpdateNetworkParamEntry& a, FsNodeUpdateNetworkParamEntry& b) {
    a.Swap(&b);
  }
  inline void Swap(FsNodeUpdateNetworkParamEntry* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FsNodeUpdateNetworkParamEntry* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FsNodeUpdateNetworkParamEntry* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FsNodeUpdateNetworkParamEntry>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FsNodeUpdateNetworkParamEntry& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FsNodeUpdateNetworkParamEntry& from) {
    FsNodeUpdateNetworkParamEntry::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FsNodeUpdateNetworkParamEntry* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yass.fs.FsNodeUpdateNetworkParamEntry";
  }
  protected:
  explicit FsNodeUpdateNetworkParamEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIpFieldNumber = 1,
    kSubjectFieldNumber = 5,
    kDistanceFieldNumber = 2,
    kPackageDelayFieldNumber = 3,
    kPackageLossFieldNumber = 4,
  };
  // string ip = 1;
  void clear_ip();
  const std::string& ip() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ip(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ip();
  PROTOBUF_NODISCARD std::string* release_ip();
  void set_allocated_ip(std::string* ip);
  private:
  const std::string& _internal_ip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ip(const std::string& value);
  std::string* _internal_mutable_ip();
  public:

  // string subject = 5;
  void clear_subject();
  const std::string& subject() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_subject(ArgT0&& arg0, ArgT... args);
  std::string* mutable_subject();
  PROTOBUF_NODISCARD std::string* release_subject();
  void set_allocated_subject(std::string* subject);
  private:
  const std::string& _internal_subject() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_subject(const std::string& value);
  std::string* _internal_mutable_subject();
  public:

  // float distance = 2;
  void clear_distance();
  float distance() const;
  void set_distance(float value);
  private:
  float _internal_distance() const;
  void _internal_set_distance(float value);
  public:

  // float package_delay = 3;
  void clear_package_delay();
  float package_delay() const;
  void set_package_delay(float value);
  private:
  float _internal_package_delay() const;
  void _internal_set_package_delay(float value);
  public:

  // float package_loss = 4;
  void clear_package_loss();
  float package_loss() const;
  void set_package_loss(float value);
  private:
  float _internal_package_loss() const;
  void _internal_set_package_loss(float value);
  public:

  // @@protoc_insertion_point(class_scope:yass.fs.FsNodeUpdateNetworkParamEntry)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ip_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr subject_;
    float distance_;
    float package_delay_;
    float package_loss_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2ffs_5fnode_5fgeo_5fupdate_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FsNodeUpdate

// string name = 1;
inline void FsNodeUpdate::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& FsNodeUpdate::name() const {
  // @@protoc_insertion_point(field_get:yass.fs.FsNodeUpdate.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FsNodeUpdate::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:yass.fs.FsNodeUpdate.name)
}
inline std::string* FsNodeUpdate::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:yass.fs.FsNodeUpdate.name)
  return _s;
}
inline const std::string& FsNodeUpdate::_internal_name() const {
  return _impl_.name_.Get();
}
inline void FsNodeUpdate::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* FsNodeUpdate::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* FsNodeUpdate::release_name() {
  // @@protoc_insertion_point(field_release:yass.fs.FsNodeUpdate.name)
  return _impl_.name_.Release();
}
inline void FsNodeUpdate::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:yass.fs.FsNodeUpdate.name)
}

// bool in_shadow = 2;
inline void FsNodeUpdate::clear_in_shadow() {
  _impl_.in_shadow_ = false;
}
inline bool FsNodeUpdate::_internal_in_shadow() const {
  return _impl_.in_shadow_;
}
inline bool FsNodeUpdate::in_shadow() const {
  // @@protoc_insertion_point(field_get:yass.fs.FsNodeUpdate.in_shadow)
  return _internal_in_shadow();
}
inline void FsNodeUpdate::_internal_set_in_shadow(bool value) {
  
  _impl_.in_shadow_ = value;
}
inline void FsNodeUpdate::set_in_shadow(bool value) {
  _internal_set_in_shadow(value);
  // @@protoc_insertion_point(field_set:yass.fs.FsNodeUpdate.in_shadow)
}

// string pos_str = 3;
inline void FsNodeUpdate::clear_pos_str() {
  _impl_.pos_str_.ClearToEmpty();
}
inline const std::string& FsNodeUpdate::pos_str() const {
  // @@protoc_insertion_point(field_get:yass.fs.FsNodeUpdate.pos_str)
  return _internal_pos_str();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FsNodeUpdate::set_pos_str(ArgT0&& arg0, ArgT... args) {
 
 _impl_.pos_str_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:yass.fs.FsNodeUpdate.pos_str)
}
inline std::string* FsNodeUpdate::mutable_pos_str() {
  std::string* _s = _internal_mutable_pos_str();
  // @@protoc_insertion_point(field_mutable:yass.fs.FsNodeUpdate.pos_str)
  return _s;
}
inline const std::string& FsNodeUpdate::_internal_pos_str() const {
  return _impl_.pos_str_.Get();
}
inline void FsNodeUpdate::_internal_set_pos_str(const std::string& value) {
  
  _impl_.pos_str_.Set(value, GetArenaForAllocation());
}
inline std::string* FsNodeUpdate::_internal_mutable_pos_str() {
  
  return _impl_.pos_str_.Mutable(GetArenaForAllocation());
}
inline std::string* FsNodeUpdate::release_pos_str() {
  // @@protoc_insertion_point(field_release:yass.fs.FsNodeUpdate.pos_str)
  return _impl_.pos_str_.Release();
}
inline void FsNodeUpdate::set_allocated_pos_str(std::string* pos_str) {
  if (pos_str != nullptr) {
    
  } else {
    
  }
  _impl_.pos_str_.SetAllocated(pos_str, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.pos_str_.IsDefault()) {
    _impl_.pos_str_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:yass.fs.FsNodeUpdate.pos_str)
}

// float x = 4;
inline void FsNodeUpdate::clear_x() {
  _impl_.x_ = 0;
}
inline float FsNodeUpdate::_internal_x() const {
  return _impl_.x_;
}
inline float FsNodeUpdate::x() const {
  // @@protoc_insertion_point(field_get:yass.fs.FsNodeUpdate.x)
  return _internal_x();
}
inline void FsNodeUpdate::_internal_set_x(float value) {
  
  _impl_.x_ = value;
}
inline void FsNodeUpdate::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:yass.fs.FsNodeUpdate.x)
}

// float y = 5;
inline void FsNodeUpdate::clear_y() {
  _impl_.y_ = 0;
}
inline float FsNodeUpdate::_internal_y() const {
  return _impl_.y_;
}
inline float FsNodeUpdate::y() const {
  // @@protoc_insertion_point(field_get:yass.fs.FsNodeUpdate.y)
  return _internal_y();
}
inline void FsNodeUpdate::_internal_set_y(float value) {
  
  _impl_.y_ = value;
}
inline void FsNodeUpdate::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:yass.fs.FsNodeUpdate.y)
}

// float z = 6;
inline void FsNodeUpdate::clear_z() {
  _impl_.z_ = 0;
}
inline float FsNodeUpdate::_internal_z() const {
  return _impl_.z_;
}
inline float FsNodeUpdate::z() const {
  // @@protoc_insertion_point(field_get:yass.fs.FsNodeUpdate.z)
  return _internal_z();
}
inline void FsNodeUpdate::_internal_set_z(float value) {
  
  _impl_.z_ = value;
}
inline void FsNodeUpdate::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:yass.fs.FsNodeUpdate.z)
}

// float lat = 7;
inline void FsNodeUpdate::clear_lat() {
  _impl_.lat_ = 0;
}
inline float FsNodeUpdate::_internal_lat() const {
  return _impl_.lat_;
}
inline float FsNodeUpdate::lat() const {
  // @@protoc_insertion_point(field_get:yass.fs.FsNodeUpdate.lat)
  return _internal_lat();
}
inline void FsNodeUpdate::_internal_set_lat(float value) {
  
  _impl_.lat_ = value;
}
inline void FsNodeUpdate::set_lat(float value) {
  _internal_set_lat(value);
  // @@protoc_insertion_point(field_set:yass.fs.FsNodeUpdate.lat)
}

// float lng = 8;
inline void FsNodeUpdate::clear_lng() {
  _impl_.lng_ = 0;
}
inline float FsNodeUpdate::_internal_lng() const {
  return _impl_.lng_;
}
inline float FsNodeUpdate::lng() const {
  // @@protoc_insertion_point(field_get:yass.fs.FsNodeUpdate.lng)
  return _internal_lng();
}
inline void FsNodeUpdate::_internal_set_lng(float value) {
  
  _impl_.lng_ = value;
}
inline void FsNodeUpdate::set_lng(float value) {
  _internal_set_lng(value);
  // @@protoc_insertion_point(field_set:yass.fs.FsNodeUpdate.lng)
}

// float alt = 9;
inline void FsNodeUpdate::clear_alt() {
  _impl_.alt_ = 0;
}
inline float FsNodeUpdate::_internal_alt() const {
  return _impl_.alt_;
}
inline float FsNodeUpdate::alt() const {
  // @@protoc_insertion_point(field_get:yass.fs.FsNodeUpdate.alt)
  return _internal_alt();
}
inline void FsNodeUpdate::_internal_set_alt(float value) {
  
  _impl_.alt_ = value;
}
inline void FsNodeUpdate::set_alt(float value) {
  _internal_set_alt(value);
  // @@protoc_insertion_point(field_set:yass.fs.FsNodeUpdate.alt)
}

// repeated .yass.fs.FsNodeUpdateNetworkParamEntry network_params = 10;
inline int FsNodeUpdate::_internal_network_params_size() const {
  return _impl_.network_params_.size();
}
inline int FsNodeUpdate::network_params_size() const {
  return _internal_network_params_size();
}
inline void FsNodeUpdate::clear_network_params() {
  _impl_.network_params_.Clear();
}
inline ::yass::fs::FsNodeUpdateNetworkParamEntry* FsNodeUpdate::mutable_network_params(int index) {
  // @@protoc_insertion_point(field_mutable:yass.fs.FsNodeUpdate.network_params)
  return _impl_.network_params_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::yass::fs::FsNodeUpdateNetworkParamEntry >*
FsNodeUpdate::mutable_network_params() {
  // @@protoc_insertion_point(field_mutable_list:yass.fs.FsNodeUpdate.network_params)
  return &_impl_.network_params_;
}
inline const ::yass::fs::FsNodeUpdateNetworkParamEntry& FsNodeUpdate::_internal_network_params(int index) const {
  return _impl_.network_params_.Get(index);
}
inline const ::yass::fs::FsNodeUpdateNetworkParamEntry& FsNodeUpdate::network_params(int index) const {
  // @@protoc_insertion_point(field_get:yass.fs.FsNodeUpdate.network_params)
  return _internal_network_params(index);
}
inline ::yass::fs::FsNodeUpdateNetworkParamEntry* FsNodeUpdate::_internal_add_network_params() {
  return _impl_.network_params_.Add();
}
inline ::yass::fs::FsNodeUpdateNetworkParamEntry* FsNodeUpdate::add_network_params() {
  ::yass::fs::FsNodeUpdateNetworkParamEntry* _add = _internal_add_network_params();
  // @@protoc_insertion_point(field_add:yass.fs.FsNodeUpdate.network_params)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::yass::fs::FsNodeUpdateNetworkParamEntry >&
FsNodeUpdate::network_params() const {
  // @@protoc_insertion_point(field_list:yass.fs.FsNodeUpdate.network_params)
  return _impl_.network_params_;
}

// int64 updated_unix_millis = 11;
inline void FsNodeUpdate::clear_updated_unix_millis() {
  _impl_.updated_unix_millis_ = int64_t{0};
}
inline int64_t FsNodeUpdate::_internal_updated_unix_millis() const {
  return _impl_.updated_unix_millis_;
}
inline int64_t FsNodeUpdate::updated_unix_millis() const {
  // @@protoc_insertion_point(field_get:yass.fs.FsNodeUpdate.updated_unix_millis)
  return _internal_updated_unix_millis();
}
inline void FsNodeUpdate::_internal_set_updated_unix_millis(int64_t value) {
  
  _impl_.updated_unix_millis_ = value;
}
inline void FsNodeUpdate::set_updated_unix_millis(int64_t value) {
  _internal_set_updated_unix_millis(value);
  // @@protoc_insertion_point(field_set:yass.fs.FsNodeUpdate.updated_unix_millis)
}

// -------------------------------------------------------------------

// FsNodeUpdateNetworkParamEntry

// string ip = 1;
inline void FsNodeUpdateNetworkParamEntry::clear_ip() {
  _impl_.ip_.ClearToEmpty();
}
inline const std::string& FsNodeUpdateNetworkParamEntry::ip() const {
  // @@protoc_insertion_point(field_get:yass.fs.FsNodeUpdateNetworkParamEntry.ip)
  return _internal_ip();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FsNodeUpdateNetworkParamEntry::set_ip(ArgT0&& arg0, ArgT... args) {
 
 _impl_.ip_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:yass.fs.FsNodeUpdateNetworkParamEntry.ip)
}
inline std::string* FsNodeUpdateNetworkParamEntry::mutable_ip() {
  std::string* _s = _internal_mutable_ip();
  // @@protoc_insertion_point(field_mutable:yass.fs.FsNodeUpdateNetworkParamEntry.ip)
  return _s;
}
inline const std::string& FsNodeUpdateNetworkParamEntry::_internal_ip() const {
  return _impl_.ip_.Get();
}
inline void FsNodeUpdateNetworkParamEntry::_internal_set_ip(const std::string& value) {
  
  _impl_.ip_.Set(value, GetArenaForAllocation());
}
inline std::string* FsNodeUpdateNetworkParamEntry::_internal_mutable_ip() {
  
  return _impl_.ip_.Mutable(GetArenaForAllocation());
}
inline std::string* FsNodeUpdateNetworkParamEntry::release_ip() {
  // @@protoc_insertion_point(field_release:yass.fs.FsNodeUpdateNetworkParamEntry.ip)
  return _impl_.ip_.Release();
}
inline void FsNodeUpdateNetworkParamEntry::set_allocated_ip(std::string* ip) {
  if (ip != nullptr) {
    
  } else {
    
  }
  _impl_.ip_.SetAllocated(ip, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ip_.IsDefault()) {
    _impl_.ip_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:yass.fs.FsNodeUpdateNetworkParamEntry.ip)
}

// float distance = 2;
inline void FsNodeUpdateNetworkParamEntry::clear_distance() {
  _impl_.distance_ = 0;
}
inline float FsNodeUpdateNetworkParamEntry::_internal_distance() const {
  return _impl_.distance_;
}
inline float FsNodeUpdateNetworkParamEntry::distance() const {
  // @@protoc_insertion_point(field_get:yass.fs.FsNodeUpdateNetworkParamEntry.distance)
  return _internal_distance();
}
inline void FsNodeUpdateNetworkParamEntry::_internal_set_distance(float value) {
  
  _impl_.distance_ = value;
}
inline void FsNodeUpdateNetworkParamEntry::set_distance(float value) {
  _internal_set_distance(value);
  // @@protoc_insertion_point(field_set:yass.fs.FsNodeUpdateNetworkParamEntry.distance)
}

// float package_delay = 3;
inline void FsNodeUpdateNetworkParamEntry::clear_package_delay() {
  _impl_.package_delay_ = 0;
}
inline float FsNodeUpdateNetworkParamEntry::_internal_package_delay() const {
  return _impl_.package_delay_;
}
inline float FsNodeUpdateNetworkParamEntry::package_delay() const {
  // @@protoc_insertion_point(field_get:yass.fs.FsNodeUpdateNetworkParamEntry.package_delay)
  return _internal_package_delay();
}
inline void FsNodeUpdateNetworkParamEntry::_internal_set_package_delay(float value) {
  
  _impl_.package_delay_ = value;
}
inline void FsNodeUpdateNetworkParamEntry::set_package_delay(float value) {
  _internal_set_package_delay(value);
  // @@protoc_insertion_point(field_set:yass.fs.FsNodeUpdateNetworkParamEntry.package_delay)
}

// float package_loss = 4;
inline void FsNodeUpdateNetworkParamEntry::clear_package_loss() {
  _impl_.package_loss_ = 0;
}
inline float FsNodeUpdateNetworkParamEntry::_internal_package_loss() const {
  return _impl_.package_loss_;
}
inline float FsNodeUpdateNetworkParamEntry::package_loss() const {
  // @@protoc_insertion_point(field_get:yass.fs.FsNodeUpdateNetworkParamEntry.package_loss)
  return _internal_package_loss();
}
inline void FsNodeUpdateNetworkParamEntry::_internal_set_package_loss(float value) {
  
  _impl_.package_loss_ = value;
}
inline void FsNodeUpdateNetworkParamEntry::set_package_loss(float value) {
  _internal_set_package_loss(value);
  // @@protoc_insertion_point(field_set:yass.fs.FsNodeUpdateNetworkParamEntry.package_loss)
}

// string subject = 5;
inline void FsNodeUpdateNetworkParamEntry::clear_subject() {
  _impl_.subject_.ClearToEmpty();
}
inline const std::string& FsNodeUpdateNetworkParamEntry::subject() const {
  // @@protoc_insertion_point(field_get:yass.fs.FsNodeUpdateNetworkParamEntry.subject)
  return _internal_subject();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FsNodeUpdateNetworkParamEntry::set_subject(ArgT0&& arg0, ArgT... args) {
 
 _impl_.subject_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:yass.fs.FsNodeUpdateNetworkParamEntry.subject)
}
inline std::string* FsNodeUpdateNetworkParamEntry::mutable_subject() {
  std::string* _s = _internal_mutable_subject();
  // @@protoc_insertion_point(field_mutable:yass.fs.FsNodeUpdateNetworkParamEntry.subject)
  return _s;
}
inline const std::string& FsNodeUpdateNetworkParamEntry::_internal_subject() const {
  return _impl_.subject_.Get();
}
inline void FsNodeUpdateNetworkParamEntry::_internal_set_subject(const std::string& value) {
  
  _impl_.subject_.Set(value, GetArenaForAllocation());
}
inline std::string* FsNodeUpdateNetworkParamEntry::_internal_mutable_subject() {
  
  return _impl_.subject_.Mutable(GetArenaForAllocation());
}
inline std::string* FsNodeUpdateNetworkParamEntry::release_subject() {
  // @@protoc_insertion_point(field_release:yass.fs.FsNodeUpdateNetworkParamEntry.subject)
  return _impl_.subject_.Release();
}
inline void FsNodeUpdateNetworkParamEntry::set_allocated_subject(std::string* subject) {
  if (subject != nullptr) {
    
  } else {
    
  }
  _impl_.subject_.SetAllocated(subject, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.subject_.IsDefault()) {
    _impl_.subject_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:yass.fs.FsNodeUpdateNetworkParamEntry.subject)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace fs
}  // namespace yass

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_proto_2ffs_5fnode_5fgeo_5fupdate_2eproto
