// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/fs_node_online_state.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_2ffs_5fnode_5fonline_5fstate_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_proto_2ffs_5fnode_5fonline_5fstate_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proto_2ffs_5fnode_5fonline_5fstate_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2ffs_5fnode_5fonline_5fstate_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2ffs_5fnode_5fonline_5fstate_2eproto;
namespace yass {
namespace fs {
class FsNodeId;
struct FsNodeIdDefaultTypeInternal;
extern FsNodeIdDefaultTypeInternal _FsNodeId_default_instance_;
class FsNodeOnlineState;
struct FsNodeOnlineStateDefaultTypeInternal;
extern FsNodeOnlineStateDefaultTypeInternal _FsNodeOnlineState_default_instance_;
}  // namespace fs
}  // namespace yass
PROTOBUF_NAMESPACE_OPEN
template<> ::yass::fs::FsNodeId* Arena::CreateMaybeMessage<::yass::fs::FsNodeId>(Arena*);
template<> ::yass::fs::FsNodeOnlineState* Arena::CreateMaybeMessage<::yass::fs::FsNodeOnlineState>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace yass {
namespace fs {

// ===================================================================

class FsNodeId final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yass.fs.FsNodeId) */ {
 public:
  inline FsNodeId() : FsNodeId(nullptr) {}
  ~FsNodeId() override;
  explicit PROTOBUF_CONSTEXPR FsNodeId(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FsNodeId(const FsNodeId& from);
  FsNodeId(FsNodeId&& from) noexcept
    : FsNodeId() {
    *this = ::std::move(from);
  }

  inline FsNodeId& operator=(const FsNodeId& from) {
    CopyFrom(from);
    return *this;
  }
  inline FsNodeId& operator=(FsNodeId&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FsNodeId& default_instance() {
    return *internal_default_instance();
  }
  static inline const FsNodeId* internal_default_instance() {
    return reinterpret_cast<const FsNodeId*>(
               &_FsNodeId_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FsNodeId& a, FsNodeId& b) {
    a.Swap(&b);
  }
  inline void Swap(FsNodeId* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FsNodeId* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FsNodeId* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FsNodeId>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FsNodeId& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FsNodeId& from) {
    FsNodeId::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FsNodeId* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yass.fs.FsNodeId";
  }
  protected:
  explicit FsNodeId(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kExperimentFieldNumber = 2,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string experiment = 2;
  void clear_experiment();
  const std::string& experiment() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_experiment(ArgT0&& arg0, ArgT... args);
  std::string* mutable_experiment();
  PROTOBUF_NODISCARD std::string* release_experiment();
  void set_allocated_experiment(std::string* experiment);
  private:
  const std::string& _internal_experiment() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_experiment(const std::string& value);
  std::string* _internal_mutable_experiment();
  public:

  // @@protoc_insertion_point(class_scope:yass.fs.FsNodeId)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr experiment_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2ffs_5fnode_5fonline_5fstate_2eproto;
};
// -------------------------------------------------------------------

class FsNodeOnlineState final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yass.fs.FsNodeOnlineState) */ {
 public:
  inline FsNodeOnlineState() : FsNodeOnlineState(nullptr) {}
  ~FsNodeOnlineState() override;
  explicit PROTOBUF_CONSTEXPR FsNodeOnlineState(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FsNodeOnlineState(const FsNodeOnlineState& from);
  FsNodeOnlineState(FsNodeOnlineState&& from) noexcept
    : FsNodeOnlineState() {
    *this = ::std::move(from);
  }

  inline FsNodeOnlineState& operator=(const FsNodeOnlineState& from) {
    CopyFrom(from);
    return *this;
  }
  inline FsNodeOnlineState& operator=(FsNodeOnlineState&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FsNodeOnlineState& default_instance() {
    return *internal_default_instance();
  }
  static inline const FsNodeOnlineState* internal_default_instance() {
    return reinterpret_cast<const FsNodeOnlineState*>(
               &_FsNodeOnlineState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(FsNodeOnlineState& a, FsNodeOnlineState& b) {
    a.Swap(&b);
  }
  inline void Swap(FsNodeOnlineState* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FsNodeOnlineState* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FsNodeOnlineState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FsNodeOnlineState>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FsNodeOnlineState& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FsNodeOnlineState& from) {
    FsNodeOnlineState::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FsNodeOnlineState* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yass.fs.FsNodeOnlineState";
  }
  protected:
  explicit FsNodeOnlineState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIpFieldNumber = 2,
    kFsNodeIdFieldNumber = 1,
    kOnlineFieldNumber = 3,
  };
  // string ip = 2;
  void clear_ip();
  const std::string& ip() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ip(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ip();
  PROTOBUF_NODISCARD std::string* release_ip();
  void set_allocated_ip(std::string* ip);
  private:
  const std::string& _internal_ip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ip(const std::string& value);
  std::string* _internal_mutable_ip();
  public:

  // .yass.fs.FsNodeId fsNodeId = 1;
  bool has_fsnodeid() const;
  private:
  bool _internal_has_fsnodeid() const;
  public:
  void clear_fsnodeid();
  const ::yass::fs::FsNodeId& fsnodeid() const;
  PROTOBUF_NODISCARD ::yass::fs::FsNodeId* release_fsnodeid();
  ::yass::fs::FsNodeId* mutable_fsnodeid();
  void set_allocated_fsnodeid(::yass::fs::FsNodeId* fsnodeid);
  private:
  const ::yass::fs::FsNodeId& _internal_fsnodeid() const;
  ::yass::fs::FsNodeId* _internal_mutable_fsnodeid();
  public:
  void unsafe_arena_set_allocated_fsnodeid(
      ::yass::fs::FsNodeId* fsnodeid);
  ::yass::fs::FsNodeId* unsafe_arena_release_fsnodeid();

  // bool online = 3;
  void clear_online();
  bool online() const;
  void set_online(bool value);
  private:
  bool _internal_online() const;
  void _internal_set_online(bool value);
  public:

  // @@protoc_insertion_point(class_scope:yass.fs.FsNodeOnlineState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ip_;
    ::yass::fs::FsNodeId* fsnodeid_;
    bool online_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2ffs_5fnode_5fonline_5fstate_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FsNodeId

// string name = 1;
inline void FsNodeId::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& FsNodeId::name() const {
  // @@protoc_insertion_point(field_get:yass.fs.FsNodeId.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FsNodeId::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:yass.fs.FsNodeId.name)
}
inline std::string* FsNodeId::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:yass.fs.FsNodeId.name)
  return _s;
}
inline const std::string& FsNodeId::_internal_name() const {
  return _impl_.name_.Get();
}
inline void FsNodeId::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* FsNodeId::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* FsNodeId::release_name() {
  // @@protoc_insertion_point(field_release:yass.fs.FsNodeId.name)
  return _impl_.name_.Release();
}
inline void FsNodeId::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:yass.fs.FsNodeId.name)
}

// string experiment = 2;
inline void FsNodeId::clear_experiment() {
  _impl_.experiment_.ClearToEmpty();
}
inline const std::string& FsNodeId::experiment() const {
  // @@protoc_insertion_point(field_get:yass.fs.FsNodeId.experiment)
  return _internal_experiment();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FsNodeId::set_experiment(ArgT0&& arg0, ArgT... args) {
 
 _impl_.experiment_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:yass.fs.FsNodeId.experiment)
}
inline std::string* FsNodeId::mutable_experiment() {
  std::string* _s = _internal_mutable_experiment();
  // @@protoc_insertion_point(field_mutable:yass.fs.FsNodeId.experiment)
  return _s;
}
inline const std::string& FsNodeId::_internal_experiment() const {
  return _impl_.experiment_.Get();
}
inline void FsNodeId::_internal_set_experiment(const std::string& value) {
  
  _impl_.experiment_.Set(value, GetArenaForAllocation());
}
inline std::string* FsNodeId::_internal_mutable_experiment() {
  
  return _impl_.experiment_.Mutable(GetArenaForAllocation());
}
inline std::string* FsNodeId::release_experiment() {
  // @@protoc_insertion_point(field_release:yass.fs.FsNodeId.experiment)
  return _impl_.experiment_.Release();
}
inline void FsNodeId::set_allocated_experiment(std::string* experiment) {
  if (experiment != nullptr) {
    
  } else {
    
  }
  _impl_.experiment_.SetAllocated(experiment, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.experiment_.IsDefault()) {
    _impl_.experiment_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:yass.fs.FsNodeId.experiment)
}

// -------------------------------------------------------------------

// FsNodeOnlineState

// .yass.fs.FsNodeId fsNodeId = 1;
inline bool FsNodeOnlineState::_internal_has_fsnodeid() const {
  return this != internal_default_instance() && _impl_.fsnodeid_ != nullptr;
}
inline bool FsNodeOnlineState::has_fsnodeid() const {
  return _internal_has_fsnodeid();
}
inline void FsNodeOnlineState::clear_fsnodeid() {
  if (GetArenaForAllocation() == nullptr && _impl_.fsnodeid_ != nullptr) {
    delete _impl_.fsnodeid_;
  }
  _impl_.fsnodeid_ = nullptr;
}
inline const ::yass::fs::FsNodeId& FsNodeOnlineState::_internal_fsnodeid() const {
  const ::yass::fs::FsNodeId* p = _impl_.fsnodeid_;
  return p != nullptr ? *p : reinterpret_cast<const ::yass::fs::FsNodeId&>(
      ::yass::fs::_FsNodeId_default_instance_);
}
inline const ::yass::fs::FsNodeId& FsNodeOnlineState::fsnodeid() const {
  // @@protoc_insertion_point(field_get:yass.fs.FsNodeOnlineState.fsNodeId)
  return _internal_fsnodeid();
}
inline void FsNodeOnlineState::unsafe_arena_set_allocated_fsnodeid(
    ::yass::fs::FsNodeId* fsnodeid) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.fsnodeid_);
  }
  _impl_.fsnodeid_ = fsnodeid;
  if (fsnodeid) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:yass.fs.FsNodeOnlineState.fsNodeId)
}
inline ::yass::fs::FsNodeId* FsNodeOnlineState::release_fsnodeid() {
  
  ::yass::fs::FsNodeId* temp = _impl_.fsnodeid_;
  _impl_.fsnodeid_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::yass::fs::FsNodeId* FsNodeOnlineState::unsafe_arena_release_fsnodeid() {
  // @@protoc_insertion_point(field_release:yass.fs.FsNodeOnlineState.fsNodeId)
  
  ::yass::fs::FsNodeId* temp = _impl_.fsnodeid_;
  _impl_.fsnodeid_ = nullptr;
  return temp;
}
inline ::yass::fs::FsNodeId* FsNodeOnlineState::_internal_mutable_fsnodeid() {
  
  if (_impl_.fsnodeid_ == nullptr) {
    auto* p = CreateMaybeMessage<::yass::fs::FsNodeId>(GetArenaForAllocation());
    _impl_.fsnodeid_ = p;
  }
  return _impl_.fsnodeid_;
}
inline ::yass::fs::FsNodeId* FsNodeOnlineState::mutable_fsnodeid() {
  ::yass::fs::FsNodeId* _msg = _internal_mutable_fsnodeid();
  // @@protoc_insertion_point(field_mutable:yass.fs.FsNodeOnlineState.fsNodeId)
  return _msg;
}
inline void FsNodeOnlineState::set_allocated_fsnodeid(::yass::fs::FsNodeId* fsnodeid) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.fsnodeid_;
  }
  if (fsnodeid) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(fsnodeid);
    if (message_arena != submessage_arena) {
      fsnodeid = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, fsnodeid, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.fsnodeid_ = fsnodeid;
  // @@protoc_insertion_point(field_set_allocated:yass.fs.FsNodeOnlineState.fsNodeId)
}

// string ip = 2;
inline void FsNodeOnlineState::clear_ip() {
  _impl_.ip_.ClearToEmpty();
}
inline const std::string& FsNodeOnlineState::ip() const {
  // @@protoc_insertion_point(field_get:yass.fs.FsNodeOnlineState.ip)
  return _internal_ip();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FsNodeOnlineState::set_ip(ArgT0&& arg0, ArgT... args) {
 
 _impl_.ip_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:yass.fs.FsNodeOnlineState.ip)
}
inline std::string* FsNodeOnlineState::mutable_ip() {
  std::string* _s = _internal_mutable_ip();
  // @@protoc_insertion_point(field_mutable:yass.fs.FsNodeOnlineState.ip)
  return _s;
}
inline const std::string& FsNodeOnlineState::_internal_ip() const {
  return _impl_.ip_.Get();
}
inline void FsNodeOnlineState::_internal_set_ip(const std::string& value) {
  
  _impl_.ip_.Set(value, GetArenaForAllocation());
}
inline std::string* FsNodeOnlineState::_internal_mutable_ip() {
  
  return _impl_.ip_.Mutable(GetArenaForAllocation());
}
inline std::string* FsNodeOnlineState::release_ip() {
  // @@protoc_insertion_point(field_release:yass.fs.FsNodeOnlineState.ip)
  return _impl_.ip_.Release();
}
inline void FsNodeOnlineState::set_allocated_ip(std::string* ip) {
  if (ip != nullptr) {
    
  } else {
    
  }
  _impl_.ip_.SetAllocated(ip, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ip_.IsDefault()) {
    _impl_.ip_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:yass.fs.FsNodeOnlineState.ip)
}

// bool online = 3;
inline void FsNodeOnlineState::clear_online() {
  _impl_.online_ = false;
}
inline bool FsNodeOnlineState::_internal_online() const {
  return _impl_.online_;
}
inline bool FsNodeOnlineState::online() const {
  // @@protoc_insertion_point(field_get:yass.fs.FsNodeOnlineState.online)
  return _internal_online();
}
inline void FsNodeOnlineState::_internal_set_online(bool value) {
  
  _impl_.online_ = value;
}
inline void FsNodeOnlineState::set_online(bool value) {
  _internal_set_online(value);
  // @@protoc_insertion_point(field_set:yass.fs.FsNodeOnlineState.online)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace fs
}  // namespace yass

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_proto_2ffs_5fnode_5fonline_5fstate_2eproto
