// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: proto/fs_node_online_state.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FsNodeId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Experiment    string                 `protobuf:"bytes,2,opt,name=experiment,proto3" json:"experiment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsNodeId) Reset() {
	*x = FsNodeId{}
	mi := &file_proto_fs_node_online_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsNodeId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsNodeId) ProtoMessage() {}

func (x *FsNodeId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fs_node_online_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsNodeId.ProtoReflect.Descriptor instead.
func (*FsNodeId) Descriptor() ([]byte, []int) {
	return file_proto_fs_node_online_state_proto_rawDescGZIP(), []int{0}
}

func (x *FsNodeId) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FsNodeId) GetExperiment() string {
	if x != nil {
		return x.Experiment
	}
	return ""
}

type FsNodeOnlineState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FsNodeId      *FsNodeId              `protobuf:"bytes,1,opt,name=fsNodeId,proto3" json:"fsNodeId,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Online        bool                   `protobuf:"varint,3,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsNodeOnlineState) Reset() {
	*x = FsNodeOnlineState{}
	mi := &file_proto_fs_node_online_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsNodeOnlineState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsNodeOnlineState) ProtoMessage() {}

func (x *FsNodeOnlineState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fs_node_online_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsNodeOnlineState.ProtoReflect.Descriptor instead.
func (*FsNodeOnlineState) Descriptor() ([]byte, []int) {
	return file_proto_fs_node_online_state_proto_rawDescGZIP(), []int{1}
}

func (x *FsNodeOnlineState) GetFsNodeId() *FsNodeId {
	if x != nil {
		return x.FsNodeId
	}
	return nil
}

func (x *FsNodeOnlineState) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *FsNodeOnlineState) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

var File_proto_fs_node_online_state_proto protoreflect.FileDescriptor

var file_proto_fs_node_online_state_proto_rawDesc = string([]byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x73, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x79, 0x61, 0x73, 0x73, 0x2e, 0x66, 0x73, 0x22, 0x3e, 0x0a, 0x08, 0x46,
	0x73, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x65,
	0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x6a, 0x0a, 0x11, 0x46,
	0x73, 0x4e, 0x6f, 0x64, 0x65, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x2d, 0x0a, 0x08, 0x66, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x79, 0x61, 0x73, 0x73, 0x2e, 0x66, 0x73, 0x2e, 0x46, 0x73, 0x4e,
	0x6f, 0x64, 0x65, 0x49, 0x64, 0x52, 0x08, 0x66, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x42, 0x43, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x75, 0x6f, 0x62, 0x69, 0x74, 0x78, 0x2f, 0x79, 0x61,
	0x73, 0x73, 0x2d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2d, 0x63, 0x6f, 0x6d, 0x70,
	0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x67, 0x6f, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_fs_node_online_state_proto_rawDescOnce sync.Once
	file_proto_fs_node_online_state_proto_rawDescData []byte
)

func file_proto_fs_node_online_state_proto_rawDescGZIP() []byte {
	file_proto_fs_node_online_state_proto_rawDescOnce.Do(func() {
		file_proto_fs_node_online_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fs_node_online_state_proto_rawDesc), len(file_proto_fs_node_online_state_proto_rawDesc)))
	})
	return file_proto_fs_node_online_state_proto_rawDescData
}

var file_proto_fs_node_online_state_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_fs_node_online_state_proto_goTypes = []any{
	(*FsNodeId)(nil),          // 0: yass.fs.FsNodeId
	(*FsNodeOnlineState)(nil), // 1: yass.fs.FsNodeOnlineState
}
var file_proto_fs_node_online_state_proto_depIdxs = []int32{
	0, // 0: yass.fs.FsNodeOnlineState.fsNodeId:type_name -> yass.fs.FsNodeId
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_fs_node_online_state_proto_init() }
func file_proto_fs_node_online_state_proto_init() {
	if File_proto_fs_node_online_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fs_node_online_state_proto_rawDesc), len(file_proto_fs_node_online_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_fs_node_online_state_proto_goTypes,
		DependencyIndexes: file_proto_fs_node_online_state_proto_depIdxs,
		MessageInfos:      file_proto_fs_node_online_state_proto_msgTypes,
	}.Build()
	File_proto_fs_node_online_state_proto = out.File
	file_proto_fs_node_online_state_proto_goTypes = nil
	file_proto_fs_node_online_state_proto_depIdxs = nil
}
