// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/traffic_stats.proto

#include "proto/traffic_stats.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace yass {
namespace fs {
PROTOBUF_CONSTEXPR TrafficStats::TrafficStats(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.ip_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.total_bytes_sent_)*/uint64_t{0u}
  , /*decltype(_impl_.total_bytes_received_)*/uint64_t{0u}
  , /*decltype(_impl_.total_packets_sent_)*/uint64_t{0u}
  , /*decltype(_impl_.total_packets_received_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TrafficStatsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TrafficStatsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TrafficStatsDefaultTypeInternal() {}
  union {
    TrafficStats _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TrafficStatsDefaultTypeInternal _TrafficStats_default_instance_;
PROTOBUF_CONSTEXPR TrafficStatsList::TrafficStatsList(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.stats_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TrafficStatsListDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TrafficStatsListDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TrafficStatsListDefaultTypeInternal() {}
  union {
    TrafficStatsList _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TrafficStatsListDefaultTypeInternal _TrafficStatsList_default_instance_;
}  // namespace fs
}  // namespace yass
static ::_pb::Metadata file_level_metadata_proto_2ftraffic_5fstats_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_proto_2ftraffic_5fstats_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_proto_2ftraffic_5fstats_2eproto = nullptr;

const uint32_t TableStruct_proto_2ftraffic_5fstats_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yass::fs::TrafficStats, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yass::fs::TrafficStats, _impl_.ip_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::TrafficStats, _impl_.total_bytes_sent_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::TrafficStats, _impl_.total_bytes_received_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::TrafficStats, _impl_.total_packets_sent_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::TrafficStats, _impl_.total_packets_received_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yass::fs::TrafficStatsList, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yass::fs::TrafficStatsList, _impl_.stats_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::yass::fs::TrafficStats)},
  { 11, -1, -1, sizeof(::yass::fs::TrafficStatsList)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::yass::fs::_TrafficStats_default_instance_._instance,
  &::yass::fs::_TrafficStatsList_default_instance_._instance,
};

const char descriptor_table_protodef_proto_2ftraffic_5fstats_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\031proto/traffic_stats.proto\022\007yass.fs\"\216\001\n"
  "\014TrafficStats\022\n\n\002ip\030\001 \001(\t\022\030\n\020total_bytes"
  "_sent\030\002 \001(\004\022\034\n\024total_bytes_received\030\003 \001("
  "\004\022\032\n\022total_packets_sent\030\004 \001(\004\022\036\n\026total_p"
  "ackets_received\030\005 \001(\004\"8\n\020TrafficStatsLis"
  "t\022$\n\005stats\030\001 \003(\0132\025.yass.fs.TrafficStatsB"
  "CZAgithub.com/duobitx/yass-internal-comp"
  "onents/go-common/proto;protob\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_proto_2ftraffic_5fstats_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_proto_2ftraffic_5fstats_2eproto = {
    false, false, 316, descriptor_table_protodef_proto_2ftraffic_5fstats_2eproto,
    "proto/traffic_stats.proto",
    &descriptor_table_proto_2ftraffic_5fstats_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_proto_2ftraffic_5fstats_2eproto::offsets,
    file_level_metadata_proto_2ftraffic_5fstats_2eproto, file_level_enum_descriptors_proto_2ftraffic_5fstats_2eproto,
    file_level_service_descriptors_proto_2ftraffic_5fstats_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_proto_2ftraffic_5fstats_2eproto_getter() {
  return &descriptor_table_proto_2ftraffic_5fstats_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_proto_2ftraffic_5fstats_2eproto(&descriptor_table_proto_2ftraffic_5fstats_2eproto);
namespace yass {
namespace fs {

// ===================================================================

class TrafficStats::_Internal {
 public:
};

TrafficStats::TrafficStats(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:yass.fs.TrafficStats)
}
TrafficStats::TrafficStats(const TrafficStats& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TrafficStats* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.ip_){}
    , decltype(_impl_.total_bytes_sent_){}
    , decltype(_impl_.total_bytes_received_){}
    , decltype(_impl_.total_packets_sent_){}
    , decltype(_impl_.total_packets_received_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.ip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_ip().empty()) {
    _this->_impl_.ip_.Set(from._internal_ip(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.total_bytes_sent_, &from._impl_.total_bytes_sent_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.total_packets_received_) -
    reinterpret_cast<char*>(&_impl_.total_bytes_sent_)) + sizeof(_impl_.total_packets_received_));
  // @@protoc_insertion_point(copy_constructor:yass.fs.TrafficStats)
}

inline void TrafficStats::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.ip_){}
    , decltype(_impl_.total_bytes_sent_){uint64_t{0u}}
    , decltype(_impl_.total_bytes_received_){uint64_t{0u}}
    , decltype(_impl_.total_packets_sent_){uint64_t{0u}}
    , decltype(_impl_.total_packets_received_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.ip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

TrafficStats::~TrafficStats() {
  // @@protoc_insertion_point(destructor:yass.fs.TrafficStats)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TrafficStats::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.ip_.Destroy();
}

void TrafficStats::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TrafficStats::Clear() {
// @@protoc_insertion_point(message_clear_start:yass.fs.TrafficStats)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.ip_.ClearToEmpty();
  ::memset(&_impl_.total_bytes_sent_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.total_packets_received_) -
      reinterpret_cast<char*>(&_impl_.total_bytes_sent_)) + sizeof(_impl_.total_packets_received_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TrafficStats::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string ip = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_ip();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "yass.fs.TrafficStats.ip"));
        } else
          goto handle_unusual;
        continue;
      // uint64 total_bytes_sent = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.total_bytes_sent_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 total_bytes_received = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.total_bytes_received_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 total_packets_sent = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.total_packets_sent_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 total_packets_received = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.total_packets_received_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TrafficStats::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yass.fs.TrafficStats)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string ip = 1;
  if (!this->_internal_ip().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_ip().data(), static_cast<int>(this->_internal_ip().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yass.fs.TrafficStats.ip");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_ip(), target);
  }

  // uint64 total_bytes_sent = 2;
  if (this->_internal_total_bytes_sent() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_total_bytes_sent(), target);
  }

  // uint64 total_bytes_received = 3;
  if (this->_internal_total_bytes_received() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(3, this->_internal_total_bytes_received(), target);
  }

  // uint64 total_packets_sent = 4;
  if (this->_internal_total_packets_sent() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(4, this->_internal_total_packets_sent(), target);
  }

  // uint64 total_packets_received = 5;
  if (this->_internal_total_packets_received() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(5, this->_internal_total_packets_received(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yass.fs.TrafficStats)
  return target;
}

size_t TrafficStats::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yass.fs.TrafficStats)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string ip = 1;
  if (!this->_internal_ip().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_ip());
  }

  // uint64 total_bytes_sent = 2;
  if (this->_internal_total_bytes_sent() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_total_bytes_sent());
  }

  // uint64 total_bytes_received = 3;
  if (this->_internal_total_bytes_received() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_total_bytes_received());
  }

  // uint64 total_packets_sent = 4;
  if (this->_internal_total_packets_sent() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_total_packets_sent());
  }

  // uint64 total_packets_received = 5;
  if (this->_internal_total_packets_received() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_total_packets_received());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TrafficStats::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TrafficStats::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TrafficStats::GetClassData() const { return &_class_data_; }


void TrafficStats::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TrafficStats*>(&to_msg);
  auto& from = static_cast<const TrafficStats&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:yass.fs.TrafficStats)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_ip().empty()) {
    _this->_internal_set_ip(from._internal_ip());
  }
  if (from._internal_total_bytes_sent() != 0) {
    _this->_internal_set_total_bytes_sent(from._internal_total_bytes_sent());
  }
  if (from._internal_total_bytes_received() != 0) {
    _this->_internal_set_total_bytes_received(from._internal_total_bytes_received());
  }
  if (from._internal_total_packets_sent() != 0) {
    _this->_internal_set_total_packets_sent(from._internal_total_packets_sent());
  }
  if (from._internal_total_packets_received() != 0) {
    _this->_internal_set_total_packets_received(from._internal_total_packets_received());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TrafficStats::CopyFrom(const TrafficStats& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yass.fs.TrafficStats)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TrafficStats::IsInitialized() const {
  return true;
}

void TrafficStats::InternalSwap(TrafficStats* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.ip_, lhs_arena,
      &other->_impl_.ip_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TrafficStats, _impl_.total_packets_received_)
      + sizeof(TrafficStats::_impl_.total_packets_received_)
      - PROTOBUF_FIELD_OFFSET(TrafficStats, _impl_.total_bytes_sent_)>(
          reinterpret_cast<char*>(&_impl_.total_bytes_sent_),
          reinterpret_cast<char*>(&other->_impl_.total_bytes_sent_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TrafficStats::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2ftraffic_5fstats_2eproto_getter, &descriptor_table_proto_2ftraffic_5fstats_2eproto_once,
      file_level_metadata_proto_2ftraffic_5fstats_2eproto[0]);
}

// ===================================================================

class TrafficStatsList::_Internal {
 public:
};

TrafficStatsList::TrafficStatsList(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:yass.fs.TrafficStatsList)
}
TrafficStatsList::TrafficStatsList(const TrafficStatsList& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TrafficStatsList* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.stats_){from._impl_.stats_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:yass.fs.TrafficStatsList)
}

inline void TrafficStatsList::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.stats_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

TrafficStatsList::~TrafficStatsList() {
  // @@protoc_insertion_point(destructor:yass.fs.TrafficStatsList)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TrafficStatsList::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.stats_.~RepeatedPtrField();
}

void TrafficStatsList::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TrafficStatsList::Clear() {
// @@protoc_insertion_point(message_clear_start:yass.fs.TrafficStatsList)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.stats_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TrafficStatsList::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .yass.fs.TrafficStats stats = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_stats(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TrafficStatsList::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yass.fs.TrafficStatsList)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .yass.fs.TrafficStats stats = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_stats_size()); i < n; i++) {
    const auto& repfield = this->_internal_stats(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yass.fs.TrafficStatsList)
  return target;
}

size_t TrafficStatsList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yass.fs.TrafficStatsList)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .yass.fs.TrafficStats stats = 1;
  total_size += 1UL * this->_internal_stats_size();
  for (const auto& msg : this->_impl_.stats_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TrafficStatsList::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TrafficStatsList::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TrafficStatsList::GetClassData() const { return &_class_data_; }


void TrafficStatsList::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TrafficStatsList*>(&to_msg);
  auto& from = static_cast<const TrafficStatsList&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:yass.fs.TrafficStatsList)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.stats_.MergeFrom(from._impl_.stats_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TrafficStatsList::CopyFrom(const TrafficStatsList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yass.fs.TrafficStatsList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TrafficStatsList::IsInitialized() const {
  return true;
}

void TrafficStatsList::InternalSwap(TrafficStatsList* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.stats_.InternalSwap(&other->_impl_.stats_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TrafficStatsList::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2ftraffic_5fstats_2eproto_getter, &descriptor_table_proto_2ftraffic_5fstats_2eproto_once,
      file_level_metadata_proto_2ftraffic_5fstats_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace fs
}  // namespace yass
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::yass::fs::TrafficStats*
Arena::CreateMaybeMessage< ::yass::fs::TrafficStats >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yass::fs::TrafficStats >(arena);
}
template<> PROTOBUF_NOINLINE ::yass::fs::TrafficStatsList*
Arena::CreateMaybeMessage< ::yass::fs::TrafficStatsList >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yass::fs::TrafficStatsList >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
