apiVersion: v1
kind: Secret
metadata:
  name: web-ui-basic-auth
type: Opaque
stringData:
  # user: eas / password: esa (APR1 hash; consumed by nginx ingress basic auth)
  auth: |
    eas:$apr1$yasswdui$Et9tG.Y.qsQSZnl33eblQ1
