// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agend_exp_end_request.proto

#include "agend_exp_end_request.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace yass {
namespace fs {
PROTOBUF_CONSTEXPR AgentExperimentEndRequest::AgentExperimentEndRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.comment_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.status_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AgentExperimentEndRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AgentExperimentEndRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AgentExperimentEndRequestDefaultTypeInternal() {}
  union {
    AgentExperimentEndRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AgentExperimentEndRequestDefaultTypeInternal _AgentExperimentEndRequest_default_instance_;
}  // namespace fs
}  // namespace yass
static ::_pb::Metadata file_level_metadata_agend_5fexp_5fend_5frequest_2eproto[1];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_agend_5fexp_5fend_5frequest_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_agend_5fexp_5fend_5frequest_2eproto = nullptr;

const uint32_t TableStruct_agend_5fexp_5fend_5frequest_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yass::fs::AgentExperimentEndRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yass::fs::AgentExperimentEndRequest, _impl_.status_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::AgentExperimentEndRequest, _impl_.comment_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::yass::fs::AgentExperimentEndRequest)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::yass::fs::_AgentExperimentEndRequest_default_instance_._instance,
};

const char descriptor_table_protodef_agend_5fexp_5fend_5frequest_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\033agend_exp_end_request.proto\022\007yass.fs\"M"
  "\n\031AgentExperimentEndRequest\022\037\n\006status\030\001 "
  "\001(\0162\017.yass.fs.Status\022\017\n\007comment\030\002 \001(\t*P\n"
  "\006Status\022\"\n\036EXPERIMENT_END_REQUEST_SUCCES"
  "S\020\000\022\"\n\036EXPERIMENT_END_REQUEST_FAILURE\020\001B"
  "CZAgithub.com/duobitx/yass-internal-comp"
  "onents/go-common/proto;protob\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_agend_5fexp_5fend_5frequest_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_agend_5fexp_5fend_5frequest_2eproto = {
    false, false, 276, descriptor_table_protodef_agend_5fexp_5fend_5frequest_2eproto,
    "agend_exp_end_request.proto",
    &descriptor_table_agend_5fexp_5fend_5frequest_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_agend_5fexp_5fend_5frequest_2eproto::offsets,
    file_level_metadata_agend_5fexp_5fend_5frequest_2eproto, file_level_enum_descriptors_agend_5fexp_5fend_5frequest_2eproto,
    file_level_service_descriptors_agend_5fexp_5fend_5frequest_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_agend_5fexp_5fend_5frequest_2eproto_getter() {
  return &descriptor_table_agend_5fexp_5fend_5frequest_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_agend_5fexp_5fend_5frequest_2eproto(&descriptor_table_agend_5fexp_5fend_5frequest_2eproto);
namespace yass {
namespace fs {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Status_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_agend_5fexp_5fend_5frequest_2eproto);
  return file_level_enum_descriptors_agend_5fexp_5fend_5frequest_2eproto[0];
}
bool Status_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class AgentExperimentEndRequest::_Internal {
 public:
};

AgentExperimentEndRequest::AgentExperimentEndRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:yass.fs.AgentExperimentEndRequest)
}
AgentExperimentEndRequest::AgentExperimentEndRequest(const AgentExperimentEndRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AgentExperimentEndRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.comment_){}
    , decltype(_impl_.status_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.comment_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.comment_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_comment().empty()) {
    _this->_impl_.comment_.Set(from._internal_comment(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.status_ = from._impl_.status_;
  // @@protoc_insertion_point(copy_constructor:yass.fs.AgentExperimentEndRequest)
}

inline void AgentExperimentEndRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.comment_){}
    , decltype(_impl_.status_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.comment_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.comment_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

AgentExperimentEndRequest::~AgentExperimentEndRequest() {
  // @@protoc_insertion_point(destructor:yass.fs.AgentExperimentEndRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AgentExperimentEndRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.comment_.Destroy();
}

void AgentExperimentEndRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AgentExperimentEndRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:yass.fs.AgentExperimentEndRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.comment_.ClearToEmpty();
  _impl_.status_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AgentExperimentEndRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .yass.fs.Status status = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_status(static_cast<::yass::fs::Status>(val));
        } else
          goto handle_unusual;
        continue;
      // string comment = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_comment();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "yass.fs.AgentExperimentEndRequest.comment"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AgentExperimentEndRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yass.fs.AgentExperimentEndRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .yass.fs.Status status = 1;
  if (this->_internal_status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_status(), target);
  }

  // string comment = 2;
  if (!this->_internal_comment().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_comment().data(), static_cast<int>(this->_internal_comment().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yass.fs.AgentExperimentEndRequest.comment");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_comment(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yass.fs.AgentExperimentEndRequest)
  return target;
}

size_t AgentExperimentEndRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yass.fs.AgentExperimentEndRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string comment = 2;
  if (!this->_internal_comment().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_comment());
  }

  // .yass.fs.Status status = 1;
  if (this->_internal_status() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_status());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AgentExperimentEndRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AgentExperimentEndRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AgentExperimentEndRequest::GetClassData() const { return &_class_data_; }


void AgentExperimentEndRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AgentExperimentEndRequest*>(&to_msg);
  auto& from = static_cast<const AgentExperimentEndRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:yass.fs.AgentExperimentEndRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_comment().empty()) {
    _this->_internal_set_comment(from._internal_comment());
  }
  if (from._internal_status() != 0) {
    _this->_internal_set_status(from._internal_status());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AgentExperimentEndRequest::CopyFrom(const AgentExperimentEndRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yass.fs.AgentExperimentEndRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AgentExperimentEndRequest::IsInitialized() const {
  return true;
}

void AgentExperimentEndRequest::InternalSwap(AgentExperimentEndRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.comment_, lhs_arena,
      &other->_impl_.comment_, rhs_arena
  );
  swap(_impl_.status_, other->_impl_.status_);
}

::PROTOBUF_NAMESPACE_ID::Metadata AgentExperimentEndRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_agend_5fexp_5fend_5frequest_2eproto_getter, &descriptor_table_agend_5fexp_5fend_5frequest_2eproto_once,
      file_level_metadata_agend_5fexp_5fend_5frequest_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace fs
}  // namespace yass
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::yass::fs::AgentExperimentEndRequest*
Arena::CreateMaybeMessage< ::yass::fs::AgentExperimentEndRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yass::fs::AgentExperimentEndRequest >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
