// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fs_node_resources.proto

#include "fs_node_resources.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace yass {
namespace fs {
PROTOBUF_CONSTEXPR FsNodeResources::FsNodeResources(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.volumes_)*/{}
  , /*decltype(_impl_.engine_containers_)*/{}
  , /*decltype(_impl_.fs_node_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.power_)*/nullptr
  , /*decltype(_impl_.updated_unix_millis_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct FsNodeResourcesDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FsNodeResourcesDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~FsNodeResourcesDefaultTypeInternal() {}
  union {
    FsNodeResources _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FsNodeResourcesDefaultTypeInternal _FsNodeResources_default_instance_;
PROTOBUF_CONSTEXPR PowerState::PowerState(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.mode_)*/0
  , /*decltype(_impl_.battery_wh_)*/0
  , /*decltype(_impl_.battery_capacity_wh_)*/0
  , /*decltype(_impl_.in_shadow_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PowerStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PowerStateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PowerStateDefaultTypeInternal() {}
  union {
    PowerState _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PowerStateDefaultTypeInternal _PowerState_default_instance_;
PROTOBUF_CONSTEXPR VolumeUsage::VolumeUsage(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.mount_path_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.used_bytes_)*/uint64_t{0u}
  , /*decltype(_impl_.capacity_bytes_)*/uint64_t{0u}
  , /*decltype(_impl_.hard_limited_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct VolumeUsageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VolumeUsageDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~VolumeUsageDefaultTypeInternal() {}
  union {
    VolumeUsage _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VolumeUsageDefaultTypeInternal _VolumeUsage_default_instance_;
PROTOBUF_CONSTEXPR ContainerCompute::ContainerCompute(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.container_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.memory_bytes_)*/uint64_t{0u}
  , /*decltype(_impl_.cpu_millicores_)*/0
  , /*decltype(_impl_.cpu_millicores_limit_)*/0
  , /*decltype(_impl_.memory_bytes_limit_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ContainerComputeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ContainerComputeDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ContainerComputeDefaultTypeInternal() {}
  union {
    ContainerCompute _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ContainerComputeDefaultTypeInternal _ContainerCompute_default_instance_;
}  // namespace fs
}  // namespace yass
static ::_pb::Metadata file_level_metadata_fs_5fnode_5fresources_2eproto[4];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_fs_5fnode_5fresources_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_fs_5fnode_5fresources_2eproto = nullptr;

const uint32_t TableStruct_fs_5fnode_5fresources_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yass::fs::FsNodeResources, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yass::fs::FsNodeResources, _impl_.fs_node_name_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::FsNodeResources, _impl_.updated_unix_millis_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::FsNodeResources, _impl_.power_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::FsNodeResources, _impl_.volumes_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::FsNodeResources, _impl_.engine_containers_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yass::fs::PowerState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yass::fs::PowerState, _impl_.mode_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::PowerState, _impl_.battery_wh_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::PowerState, _impl_.battery_capacity_wh_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::PowerState, _impl_.in_shadow_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yass::fs::VolumeUsage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yass::fs::VolumeUsage, _impl_.name_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::VolumeUsage, _impl_.mount_path_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::VolumeUsage, _impl_.used_bytes_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::VolumeUsage, _impl_.capacity_bytes_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::VolumeUsage, _impl_.hard_limited_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yass::fs::ContainerCompute, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yass::fs::ContainerCompute, _impl_.container_name_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::ContainerCompute, _impl_.cpu_millicores_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::ContainerCompute, _impl_.memory_bytes_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::ContainerCompute, _impl_.cpu_millicores_limit_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::ContainerCompute, _impl_.memory_bytes_limit_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::yass::fs::FsNodeResources)},
  { 11, -1, -1, sizeof(::yass::fs::PowerState)},
  { 21, -1, -1, sizeof(::yass::fs::VolumeUsage)},
  { 32, -1, -1, sizeof(::yass::fs::ContainerCompute)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::yass::fs::_FsNodeResources_default_instance_._instance,
  &::yass::fs::_PowerState_default_instance_._instance,
  &::yass::fs::_VolumeUsage_default_instance_._instance,
  &::yass::fs::_ContainerCompute_default_instance_._instance,
};

const char descriptor_table_protodef_fs_5fnode_5fresources_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\027fs_node_resources.proto\022\007yass.fs\"\305\001\n\017F"
  "sNodeResources\022\024\n\014fs_node_name\030\001 \001(\t\022\033\n\023"
  "updated_unix_millis\030\002 \001(\003\022\"\n\005power\030\003 \001(\013"
  "2\023.yass.fs.PowerState\022%\n\007volumes\030\004 \003(\0132\024"
  ".yass.fs.VolumeUsage\0224\n\021engine_container"
  "s\030\005 \003(\0132\031.yass.fs.ContainerCompute\"\233\001\n\nP"
  "owerState\022&\n\004mode\030\001 \001(\0162\030.yass.fs.PowerS"
  "tate.Mode\022\022\n\nbattery_wh\030\002 \001(\002\022\033\n\023battery"
  "_capacity_wh\030\003 \001(\002\022\021\n\tin_shadow\030\004 \001(\010\"!\n"
  "\004Mode\022\n\n\006NORMAL\020\000\022\r\n\tLOW_POWER\020\001\"q\n\013Volu"
  "meUsage\022\014\n\004name\030\001 \001(\t\022\022\n\nmount_path\030\002 \001("
  "\t\022\022\n\nused_bytes\030\003 \001(\004\022\026\n\016capacity_bytes\030"
  "\004 \001(\004\022\024\n\014hard_limited\030\005 \001(\010\"\222\001\n\020Containe"
  "rCompute\022\026\n\016container_name\030\001 \001(\t\022\026\n\016cpu_"
  "millicores\030\002 \001(\002\022\024\n\014memory_bytes\030\003 \001(\004\022\034"
  "\n\024cpu_millicores_limit\030\004 \001(\002\022\032\n\022memory_b"
  "ytes_limit\030\005 \001(\004BCZAgithub.com/duobitx/y"
  "ass-internal-components/go-common/proto;"
  "protob\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_fs_5fnode_5fresources_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_fs_5fnode_5fresources_2eproto = {
    false, false, 733, descriptor_table_protodef_fs_5fnode_5fresources_2eproto,
    "fs_node_resources.proto",
    &descriptor_table_fs_5fnode_5fresources_2eproto_once, nullptr, 0, 4,
    schemas, file_default_instances, TableStruct_fs_5fnode_5fresources_2eproto::offsets,
    file_level_metadata_fs_5fnode_5fresources_2eproto, file_level_enum_descriptors_fs_5fnode_5fresources_2eproto,
    file_level_service_descriptors_fs_5fnode_5fresources_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_fs_5fnode_5fresources_2eproto_getter() {
  return &descriptor_table_fs_5fnode_5fresources_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_fs_5fnode_5fresources_2eproto(&descriptor_table_fs_5fnode_5fresources_2eproto);
namespace yass {
namespace fs {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PowerState_Mode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_fs_5fnode_5fresources_2eproto);
  return file_level_enum_descriptors_fs_5fnode_5fresources_2eproto[0];
}
bool PowerState_Mode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr PowerState_Mode PowerState::NORMAL;
constexpr PowerState_Mode PowerState::LOW_POWER;
constexpr PowerState_Mode PowerState::Mode_MIN;
constexpr PowerState_Mode PowerState::Mode_MAX;
constexpr int PowerState::Mode_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class FsNodeResources::_Internal {
 public:
  static const ::yass::fs::PowerState& power(const FsNodeResources* msg);
};

const ::yass::fs::PowerState&
FsNodeResources::_Internal::power(const FsNodeResources* msg) {
  return *msg->_impl_.power_;
}
FsNodeResources::FsNodeResources(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:yass.fs.FsNodeResources)
}
FsNodeResources::FsNodeResources(const FsNodeResources& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  FsNodeResources* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.volumes_){from._impl_.volumes_}
    , decltype(_impl_.engine_containers_){from._impl_.engine_containers_}
    , decltype(_impl_.fs_node_name_){}
    , decltype(_impl_.power_){nullptr}
    , decltype(_impl_.updated_unix_millis_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.fs_node_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.fs_node_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_fs_node_name().empty()) {
    _this->_impl_.fs_node_name_.Set(from._internal_fs_node_name(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_power()) {
    _this->_impl_.power_ = new ::yass::fs::PowerState(*from._impl_.power_);
  }
  _this->_impl_.updated_unix_millis_ = from._impl_.updated_unix_millis_;
  // @@protoc_insertion_point(copy_constructor:yass.fs.FsNodeResources)
}

inline void FsNodeResources::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.volumes_){arena}
    , decltype(_impl_.engine_containers_){arena}
    , decltype(_impl_.fs_node_name_){}
    , decltype(_impl_.power_){nullptr}
    , decltype(_impl_.updated_unix_millis_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.fs_node_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.fs_node_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

FsNodeResources::~FsNodeResources() {
  // @@protoc_insertion_point(destructor:yass.fs.FsNodeResources)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void FsNodeResources::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.volumes_.~RepeatedPtrField();
  _impl_.engine_containers_.~RepeatedPtrField();
  _impl_.fs_node_name_.Destroy();
  if (this != internal_default_instance()) delete _impl_.power_;
}

void FsNodeResources::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void FsNodeResources::Clear() {
// @@protoc_insertion_point(message_clear_start:yass.fs.FsNodeResources)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.volumes_.Clear();
  _impl_.engine_containers_.Clear();
  _impl_.fs_node_name_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.power_ != nullptr) {
    delete _impl_.power_;
  }
  _impl_.power_ = nullptr;
  _impl_.updated_unix_millis_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FsNodeResources::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string fs_node_name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_fs_node_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "yass.fs.FsNodeResources.fs_node_name"));
        } else
          goto handle_unusual;
        continue;
      // int64 updated_unix_millis = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.updated_unix_millis_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .yass.fs.PowerState power = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_power(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .yass.fs.VolumeUsage volumes = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_volumes(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated .yass.fs.ContainerCompute engine_containers = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_engine_containers(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<42>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* FsNodeResources::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yass.fs.FsNodeResources)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string fs_node_name = 1;
  if (!this->_internal_fs_node_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_fs_node_name().data(), static_cast<int>(this->_internal_fs_node_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yass.fs.FsNodeResources.fs_node_name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_fs_node_name(), target);
  }

  // int64 updated_unix_millis = 2;
  if (this->_internal_updated_unix_millis() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_updated_unix_millis(), target);
  }

  // .yass.fs.PowerState power = 3;
  if (this->_internal_has_power()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::power(this),
        _Internal::power(this).GetCachedSize(), target, stream);
  }

  // repeated .yass.fs.VolumeUsage volumes = 4;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_volumes_size()); i < n; i++) {
    const auto& repfield = this->_internal_volumes(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(4, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .yass.fs.ContainerCompute engine_containers = 5;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_engine_containers_size()); i < n; i++) {
    const auto& repfield = this->_internal_engine_containers(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(5, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yass.fs.FsNodeResources)
  return target;
}

size_t FsNodeResources::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yass.fs.FsNodeResources)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .yass.fs.VolumeUsage volumes = 4;
  total_size += 1UL * this->_internal_volumes_size();
  for (const auto& msg : this->_impl_.volumes_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .yass.fs.ContainerCompute engine_containers = 5;
  total_size += 1UL * this->_internal_engine_containers_size();
  for (const auto& msg : this->_impl_.engine_containers_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string fs_node_name = 1;
  if (!this->_internal_fs_node_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_fs_node_name());
  }

  // .yass.fs.PowerState power = 3;
  if (this->_internal_has_power()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.power_);
  }

  // int64 updated_unix_millis = 2;
  if (this->_internal_updated_unix_millis() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_updated_unix_millis());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData FsNodeResources::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    FsNodeResources::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*FsNodeResources::GetClassData() const { return &_class_data_; }


void FsNodeResources::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<FsNodeResources*>(&to_msg);
  auto& from = static_cast<const FsNodeResources&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:yass.fs.FsNodeResources)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.volumes_.MergeFrom(from._impl_.volumes_);
  _this->_impl_.engine_containers_.MergeFrom(from._impl_.engine_containers_);
  if (!from._internal_fs_node_name().empty()) {
    _this->_internal_set_fs_node_name(from._internal_fs_node_name());
  }
  if (from._internal_has_power()) {
    _this->_internal_mutable_power()->::yass::fs::PowerState::MergeFrom(
        from._internal_power());
  }
  if (from._internal_updated_unix_millis() != 0) {
    _this->_internal_set_updated_unix_millis(from._internal_updated_unix_millis());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void FsNodeResources::CopyFrom(const FsNodeResources& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yass.fs.FsNodeResources)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FsNodeResources::IsInitialized() const {
  return true;
}

void FsNodeResources::InternalSwap(FsNodeResources* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.volumes_.InternalSwap(&other->_impl_.volumes_);
  _impl_.engine_containers_.InternalSwap(&other->_impl_.engine_containers_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.fs_node_name_, lhs_arena,
      &other->_impl_.fs_node_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FsNodeResources, _impl_.updated_unix_millis_)
      + sizeof(FsNodeResources::_impl_.updated_unix_millis_)
      - PROTOBUF_FIELD_OFFSET(FsNodeResources, _impl_.power_)>(
          reinterpret_cast<char*>(&_impl_.power_),
          reinterpret_cast<char*>(&other->_impl_.power_));
}

::PROTOBUF_NAMESPACE_ID::Metadata FsNodeResources::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_fs_5fnode_5fresources_2eproto_getter, &descriptor_table_fs_5fnode_5fresources_2eproto_once,
      file_level_metadata_fs_5fnode_5fresources_2eproto[0]);
}

// ===================================================================

class PowerState::_Internal {
 public:
};

PowerState::PowerState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:yass.fs.PowerState)
}
PowerState::PowerState(const PowerState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PowerState* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.mode_){}
    , decltype(_impl_.battery_wh_){}
    , decltype(_impl_.battery_capacity_wh_){}
    , decltype(_impl_.in_shadow_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.mode_, &from._impl_.mode_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.in_shadow_) -
    reinterpret_cast<char*>(&_impl_.mode_)) + sizeof(_impl_.in_shadow_));
  // @@protoc_insertion_point(copy_constructor:yass.fs.PowerState)
}

inline void PowerState::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.mode_){0}
    , decltype(_impl_.battery_wh_){0}
    , decltype(_impl_.battery_capacity_wh_){0}
    , decltype(_impl_.in_shadow_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PowerState::~PowerState() {
  // @@protoc_insertion_point(destructor:yass.fs.PowerState)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PowerState::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void PowerState::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PowerState::Clear() {
// @@protoc_insertion_point(message_clear_start:yass.fs.PowerState)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.mode_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.in_shadow_) -
      reinterpret_cast<char*>(&_impl_.mode_)) + sizeof(_impl_.in_shadow_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PowerState::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .yass.fs.PowerState.Mode mode = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_mode(static_cast<::yass::fs::PowerState_Mode>(val));
        } else
          goto handle_unusual;
        continue;
      // float battery_wh = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _impl_.battery_wh_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float battery_capacity_wh = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 29)) {
          _impl_.battery_capacity_wh_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // bool in_shadow = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.in_shadow_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PowerState::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yass.fs.PowerState)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .yass.fs.PowerState.Mode mode = 1;
  if (this->_internal_mode() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_mode(), target);
  }

  // float battery_wh = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_battery_wh = this->_internal_battery_wh();
  uint32_t raw_battery_wh;
  memcpy(&raw_battery_wh, &tmp_battery_wh, sizeof(tmp_battery_wh));
  if (raw_battery_wh != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_battery_wh(), target);
  }

  // float battery_capacity_wh = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_battery_capacity_wh = this->_internal_battery_capacity_wh();
  uint32_t raw_battery_capacity_wh;
  memcpy(&raw_battery_capacity_wh, &tmp_battery_capacity_wh, sizeof(tmp_battery_capacity_wh));
  if (raw_battery_capacity_wh != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(3, this->_internal_battery_capacity_wh(), target);
  }

  // bool in_shadow = 4;
  if (this->_internal_in_shadow() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(4, this->_internal_in_shadow(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yass.fs.PowerState)
  return target;
}

size_t PowerState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yass.fs.PowerState)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .yass.fs.PowerState.Mode mode = 1;
  if (this->_internal_mode() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_mode());
  }

  // float battery_wh = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_battery_wh = this->_internal_battery_wh();
  uint32_t raw_battery_wh;
  memcpy(&raw_battery_wh, &tmp_battery_wh, sizeof(tmp_battery_wh));
  if (raw_battery_wh != 0) {
    total_size += 1 + 4;
  }

  // float battery_capacity_wh = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_battery_capacity_wh = this->_internal_battery_capacity_wh();
  uint32_t raw_battery_capacity_wh;
  memcpy(&raw_battery_capacity_wh, &tmp_battery_capacity_wh, sizeof(tmp_battery_capacity_wh));
  if (raw_battery_capacity_wh != 0) {
    total_size += 1 + 4;
  }

  // bool in_shadow = 4;
  if (this->_internal_in_shadow() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PowerState::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PowerState::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PowerState::GetClassData() const { return &_class_data_; }


void PowerState::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PowerState*>(&to_msg);
  auto& from = static_cast<const PowerState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:yass.fs.PowerState)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_mode() != 0) {
    _this->_internal_set_mode(from._internal_mode());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_battery_wh = from._internal_battery_wh();
  uint32_t raw_battery_wh;
  memcpy(&raw_battery_wh, &tmp_battery_wh, sizeof(tmp_battery_wh));
  if (raw_battery_wh != 0) {
    _this->_internal_set_battery_wh(from._internal_battery_wh());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_battery_capacity_wh = from._internal_battery_capacity_wh();
  uint32_t raw_battery_capacity_wh;
  memcpy(&raw_battery_capacity_wh, &tmp_battery_capacity_wh, sizeof(tmp_battery_capacity_wh));
  if (raw_battery_capacity_wh != 0) {
    _this->_internal_set_battery_capacity_wh(from._internal_battery_capacity_wh());
  }
  if (from._internal_in_shadow() != 0) {
    _this->_internal_set_in_shadow(from._internal_in_shadow());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PowerState::CopyFrom(const PowerState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yass.fs.PowerState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PowerState::IsInitialized() const {
  return true;
}

void PowerState::InternalSwap(PowerState* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PowerState, _impl_.in_shadow_)
      + sizeof(PowerState::_impl_.in_shadow_)
      - PROTOBUF_FIELD_OFFSET(PowerState, _impl_.mode_)>(
          reinterpret_cast<char*>(&_impl_.mode_),
          reinterpret_cast<char*>(&other->_impl_.mode_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PowerState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_fs_5fnode_5fresources_2eproto_getter, &descriptor_table_fs_5fnode_5fresources_2eproto_once,
      file_level_metadata_fs_5fnode_5fresources_2eproto[1]);
}

// ===================================================================

class VolumeUsage::_Internal {
 public:
};

VolumeUsage::VolumeUsage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:yass.fs.VolumeUsage)
}
VolumeUsage::VolumeUsage(const VolumeUsage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  VolumeUsage* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.mount_path_){}
    , decltype(_impl_.used_bytes_){}
    , decltype(_impl_.capacity_bytes_){}
    , decltype(_impl_.hard_limited_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.mount_path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.mount_path_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_mount_path().empty()) {
    _this->_impl_.mount_path_.Set(from._internal_mount_path(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.used_bytes_, &from._impl_.used_bytes_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.hard_limited_) -
    reinterpret_cast<char*>(&_impl_.used_bytes_)) + sizeof(_impl_.hard_limited_));
  // @@protoc_insertion_point(copy_constructor:yass.fs.VolumeUsage)
}

inline void VolumeUsage::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.mount_path_){}
    , decltype(_impl_.used_bytes_){uint64_t{0u}}
    , decltype(_impl_.capacity_bytes_){uint64_t{0u}}
    , decltype(_impl_.hard_limited_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.mount_path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.mount_path_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

VolumeUsage::~VolumeUsage() {
  // @@protoc_insertion_point(destructor:yass.fs.VolumeUsage)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void VolumeUsage::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.name_.Destroy();
  _impl_.mount_path_.Destroy();
}

void VolumeUsage::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void VolumeUsage::Clear() {
// @@protoc_insertion_point(message_clear_start:yass.fs.VolumeUsage)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.mount_path_.ClearToEmpty();
  ::memset(&_impl_.used_bytes_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.hard_limited_) -
      reinterpret_cast<char*>(&_impl_.used_bytes_)) + sizeof(_impl_.hard_limited_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* VolumeUsage::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "yass.fs.VolumeUsage.name"));
        } else
          goto handle_unusual;
        continue;
      // string mount_path = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_mount_path();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "yass.fs.VolumeUsage.mount_path"));
        } else
          goto handle_unusual;
        continue;
      // uint64 used_bytes = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.used_bytes_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 capacity_bytes = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.capacity_bytes_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool hard_limited = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.hard_limited_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* VolumeUsage::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yass.fs.VolumeUsage)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yass.fs.VolumeUsage.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // string mount_path = 2;
  if (!this->_internal_mount_path().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_mount_path().data(), static_cast<int>(this->_internal_mount_path().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yass.fs.VolumeUsage.mount_path");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_mount_path(), target);
  }

  // uint64 used_bytes = 3;
  if (this->_internal_used_bytes() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(3, this->_internal_used_bytes(), target);
  }

  // uint64 capacity_bytes = 4;
  if (this->_internal_capacity_bytes() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(4, this->_internal_capacity_bytes(), target);
  }

  // bool hard_limited = 5;
  if (this->_internal_hard_limited() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(5, this->_internal_hard_limited(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yass.fs.VolumeUsage)
  return target;
}

size_t VolumeUsage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yass.fs.VolumeUsage)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // string mount_path = 2;
  if (!this->_internal_mount_path().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_mount_path());
  }

  // uint64 used_bytes = 3;
  if (this->_internal_used_bytes() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_used_bytes());
  }

  // uint64 capacity_bytes = 4;
  if (this->_internal_capacity_bytes() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_capacity_bytes());
  }

  // bool hard_limited = 5;
  if (this->_internal_hard_limited() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData VolumeUsage::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    VolumeUsage::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*VolumeUsage::GetClassData() const { return &_class_data_; }


void VolumeUsage::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<VolumeUsage*>(&to_msg);
  auto& from = static_cast<const VolumeUsage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:yass.fs.VolumeUsage)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_mount_path().empty()) {
    _this->_internal_set_mount_path(from._internal_mount_path());
  }
  if (from._internal_used_bytes() != 0) {
    _this->_internal_set_used_bytes(from._internal_used_bytes());
  }
  if (from._internal_capacity_bytes() != 0) {
    _this->_internal_set_capacity_bytes(from._internal_capacity_bytes());
  }
  if (from._internal_hard_limited() != 0) {
    _this->_internal_set_hard_limited(from._internal_hard_limited());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void VolumeUsage::CopyFrom(const VolumeUsage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yass.fs.VolumeUsage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VolumeUsage::IsInitialized() const {
  return true;
}

void VolumeUsage::InternalSwap(VolumeUsage* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.mount_path_, lhs_arena,
      &other->_impl_.mount_path_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(VolumeUsage, _impl_.hard_limited_)
      + sizeof(VolumeUsage::_impl_.hard_limited_)
      - PROTOBUF_FIELD_OFFSET(VolumeUsage, _impl_.used_bytes_)>(
          reinterpret_cast<char*>(&_impl_.used_bytes_),
          reinterpret_cast<char*>(&other->_impl_.used_bytes_));
}

::PROTOBUF_NAMESPACE_ID::Metadata VolumeUsage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_fs_5fnode_5fresources_2eproto_getter, &descriptor_table_fs_5fnode_5fresources_2eproto_once,
      file_level_metadata_fs_5fnode_5fresources_2eproto[2]);
}

// ===================================================================

class ContainerCompute::_Internal {
 public:
};

ContainerCompute::ContainerCompute(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:yass.fs.ContainerCompute)
}
ContainerCompute::ContainerCompute(const ContainerCompute& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ContainerCompute* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.container_name_){}
    , decltype(_impl_.memory_bytes_){}
    , decltype(_impl_.cpu_millicores_){}
    , decltype(_impl_.cpu_millicores_limit_){}
    , decltype(_impl_.memory_bytes_limit_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.container_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.container_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_container_name().empty()) {
    _this->_impl_.container_name_.Set(from._internal_container_name(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.memory_bytes_, &from._impl_.memory_bytes_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.memory_bytes_limit_) -
    reinterpret_cast<char*>(&_impl_.memory_bytes_)) + sizeof(_impl_.memory_bytes_limit_));
  // @@protoc_insertion_point(copy_constructor:yass.fs.ContainerCompute)
}

inline void ContainerCompute::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.container_name_){}
    , decltype(_impl_.memory_bytes_){uint64_t{0u}}
    , decltype(_impl_.cpu_millicores_){0}
    , decltype(_impl_.cpu_millicores_limit_){0}
    , decltype(_impl_.memory_bytes_limit_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.container_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.container_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ContainerCompute::~ContainerCompute() {
  // @@protoc_insertion_point(destructor:yass.fs.ContainerCompute)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ContainerCompute::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.container_name_.Destroy();
}

void ContainerCompute::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ContainerCompute::Clear() {
// @@protoc_insertion_point(message_clear_start:yass.fs.ContainerCompute)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.container_name_.ClearToEmpty();
  ::memset(&_impl_.memory_bytes_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.memory_bytes_limit_) -
      reinterpret_cast<char*>(&_impl_.memory_bytes_)) + sizeof(_impl_.memory_bytes_limit_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ContainerCompute::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string container_name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_container_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "yass.fs.ContainerCompute.container_name"));
        } else
          goto handle_unusual;
        continue;
      // float cpu_millicores = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _impl_.cpu_millicores_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // uint64 memory_bytes = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.memory_bytes_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // float cpu_millicores_limit = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 37)) {
          _impl_.cpu_millicores_limit_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // uint64 memory_bytes_limit = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.memory_bytes_limit_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ContainerCompute::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yass.fs.ContainerCompute)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string container_name = 1;
  if (!this->_internal_container_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_container_name().data(), static_cast<int>(this->_internal_container_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yass.fs.ContainerCompute.container_name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_container_name(), target);
  }

  // float cpu_millicores = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_cpu_millicores = this->_internal_cpu_millicores();
  uint32_t raw_cpu_millicores;
  memcpy(&raw_cpu_millicores, &tmp_cpu_millicores, sizeof(tmp_cpu_millicores));
  if (raw_cpu_millicores != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_cpu_millicores(), target);
  }

  // uint64 memory_bytes = 3;
  if (this->_internal_memory_bytes() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(3, this->_internal_memory_bytes(), target);
  }

  // float cpu_millicores_limit = 4;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_cpu_millicores_limit = this->_internal_cpu_millicores_limit();
  uint32_t raw_cpu_millicores_limit;
  memcpy(&raw_cpu_millicores_limit, &tmp_cpu_millicores_limit, sizeof(tmp_cpu_millicores_limit));
  if (raw_cpu_millicores_limit != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(4, this->_internal_cpu_millicores_limit(), target);
  }

  // uint64 memory_bytes_limit = 5;
  if (this->_internal_memory_bytes_limit() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(5, this->_internal_memory_bytes_limit(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yass.fs.ContainerCompute)
  return target;
}

size_t ContainerCompute::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yass.fs.ContainerCompute)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string container_name = 1;
  if (!this->_internal_container_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_container_name());
  }

  // uint64 memory_bytes = 3;
  if (this->_internal_memory_bytes() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_memory_bytes());
  }

  // float cpu_millicores = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_cpu_millicores = this->_internal_cpu_millicores();
  uint32_t raw_cpu_millicores;
  memcpy(&raw_cpu_millicores, &tmp_cpu_millicores, sizeof(tmp_cpu_millicores));
  if (raw_cpu_millicores != 0) {
    total_size += 1 + 4;
  }

  // float cpu_millicores_limit = 4;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_cpu_millicores_limit = this->_internal_cpu_millicores_limit();
  uint32_t raw_cpu_millicores_limit;
  memcpy(&raw_cpu_millicores_limit, &tmp_cpu_millicores_limit, sizeof(tmp_cpu_millicores_limit));
  if (raw_cpu_millicores_limit != 0) {
    total_size += 1 + 4;
  }

  // uint64 memory_bytes_limit = 5;
  if (this->_internal_memory_bytes_limit() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_memory_bytes_limit());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ContainerCompute::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ContainerCompute::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ContainerCompute::GetClassData() const { return &_class_data_; }


void ContainerCompute::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ContainerCompute*>(&to_msg);
  auto& from = static_cast<const ContainerCompute&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:yass.fs.ContainerCompute)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_container_name().empty()) {
    _this->_internal_set_container_name(from._internal_container_name());
  }
  if (from._internal_memory_bytes() != 0) {
    _this->_internal_set_memory_bytes(from._internal_memory_bytes());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_cpu_millicores = from._internal_cpu_millicores();
  uint32_t raw_cpu_millicores;
  memcpy(&raw_cpu_millicores, &tmp_cpu_millicores, sizeof(tmp_cpu_millicores));
  if (raw_cpu_millicores != 0) {
    _this->_internal_set_cpu_millicores(from._internal_cpu_millicores());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_cpu_millicores_limit = from._internal_cpu_millicores_limit();
  uint32_t raw_cpu_millicores_limit;
  memcpy(&raw_cpu_millicores_limit, &tmp_cpu_millicores_limit, sizeof(tmp_cpu_millicores_limit));
  if (raw_cpu_millicores_limit != 0) {
    _this->_internal_set_cpu_millicores_limit(from._internal_cpu_millicores_limit());
  }
  if (from._internal_memory_bytes_limit() != 0) {
    _this->_internal_set_memory_bytes_limit(from._internal_memory_bytes_limit());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ContainerCompute::CopyFrom(const ContainerCompute& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yass.fs.ContainerCompute)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ContainerCompute::IsInitialized() const {
  return true;
}

void ContainerCompute::InternalSwap(ContainerCompute* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.container_name_, lhs_arena,
      &other->_impl_.container_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ContainerCompute, _impl_.memory_bytes_limit_)
      + sizeof(ContainerCompute::_impl_.memory_bytes_limit_)
      - PROTOBUF_FIELD_OFFSET(ContainerCompute, _impl_.memory_bytes_)>(
          reinterpret_cast<char*>(&_impl_.memory_bytes_),
          reinterpret_cast<char*>(&other->_impl_.memory_bytes_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ContainerCompute::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_fs_5fnode_5fresources_2eproto_getter, &descriptor_table_fs_5fnode_5fresources_2eproto_once,
      file_level_metadata_fs_5fnode_5fresources_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace fs
}  // namespace yass
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::yass::fs::FsNodeResources*
Arena::CreateMaybeMessage< ::yass::fs::FsNodeResources >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yass::fs::FsNodeResources >(arena);
}
template<> PROTOBUF_NOINLINE ::yass::fs::PowerState*
Arena::CreateMaybeMessage< ::yass::fs::PowerState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yass::fs::PowerState >(arena);
}
template<> PROTOBUF_NOINLINE ::yass::fs::VolumeUsage*
Arena::CreateMaybeMessage< ::yass::fs::VolumeUsage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yass::fs::VolumeUsage >(arena);
}
template<> PROTOBUF_NOINLINE ::yass::fs::ContainerCompute*
Arena::CreateMaybeMessage< ::yass::fs::ContainerCompute >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yass::fs::ContainerCompute >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
