// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: time_update.proto

#include "time_update.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace yass {
namespace fs {
PROTOBUF_CONSTEXPR TimeUpdate::TimeUpdate(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.now_)*/int64_t{0}
  , /*decltype(_impl_.ongoing_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TimeUpdateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TimeUpdateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TimeUpdateDefaultTypeInternal() {}
  union {
    TimeUpdate _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TimeUpdateDefaultTypeInternal _TimeUpdate_default_instance_;
}  // namespace fs
}  // namespace yass
static ::_pb::Metadata file_level_metadata_time_5fupdate_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_time_5fupdate_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_time_5fupdate_2eproto = nullptr;

const uint32_t TableStruct_time_5fupdate_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yass::fs::TimeUpdate, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yass::fs::TimeUpdate, _impl_.ongoing_),
  PROTOBUF_FIELD_OFFSET(::yass::fs::TimeUpdate, _impl_.now_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::yass::fs::TimeUpdate)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::yass::fs::_TimeUpdate_default_instance_._instance,
};

const char descriptor_table_protodef_time_5fupdate_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021time_update.proto\022\007yass.fs\"*\n\nTimeUpda"
  "te\022\017\n\007ongoing\030\001 \001(\010\022\013\n\003now\030\002 \001(\003BCZAgith"
  "ub.com/duobitx/yass-internal-components/"
  "go-common/proto;protob\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_time_5fupdate_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_time_5fupdate_2eproto = {
    false, false, 149, descriptor_table_protodef_time_5fupdate_2eproto,
    "time_update.proto",
    &descriptor_table_time_5fupdate_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_time_5fupdate_2eproto::offsets,
    file_level_metadata_time_5fupdate_2eproto, file_level_enum_descriptors_time_5fupdate_2eproto,
    file_level_service_descriptors_time_5fupdate_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_time_5fupdate_2eproto_getter() {
  return &descriptor_table_time_5fupdate_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_time_5fupdate_2eproto(&descriptor_table_time_5fupdate_2eproto);
namespace yass {
namespace fs {

// ===================================================================

class TimeUpdate::_Internal {
 public:
};

TimeUpdate::TimeUpdate(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:yass.fs.TimeUpdate)
}
TimeUpdate::TimeUpdate(const TimeUpdate& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TimeUpdate* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.now_){}
    , decltype(_impl_.ongoing_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.now_, &from._impl_.now_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.ongoing_) -
    reinterpret_cast<char*>(&_impl_.now_)) + sizeof(_impl_.ongoing_));
  // @@protoc_insertion_point(copy_constructor:yass.fs.TimeUpdate)
}

inline void TimeUpdate::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.now_){int64_t{0}}
    , decltype(_impl_.ongoing_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

TimeUpdate::~TimeUpdate() {
  // @@protoc_insertion_point(destructor:yass.fs.TimeUpdate)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TimeUpdate::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void TimeUpdate::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TimeUpdate::Clear() {
// @@protoc_insertion_point(message_clear_start:yass.fs.TimeUpdate)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.now_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.ongoing_) -
      reinterpret_cast<char*>(&_impl_.now_)) + sizeof(_impl_.ongoing_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TimeUpdate::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool ongoing = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.ongoing_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 now = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.now_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TimeUpdate::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yass.fs.TimeUpdate)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool ongoing = 1;
  if (this->_internal_ongoing() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_ongoing(), target);
  }

  // int64 now = 2;
  if (this->_internal_now() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_now(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yass.fs.TimeUpdate)
  return target;
}

size_t TimeUpdate::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yass.fs.TimeUpdate)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 now = 2;
  if (this->_internal_now() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_now());
  }

  // bool ongoing = 1;
  if (this->_internal_ongoing() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TimeUpdate::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TimeUpdate::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TimeUpdate::GetClassData() const { return &_class_data_; }


void TimeUpdate::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TimeUpdate*>(&to_msg);
  auto& from = static_cast<const TimeUpdate&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:yass.fs.TimeUpdate)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_now() != 0) {
    _this->_internal_set_now(from._internal_now());
  }
  if (from._internal_ongoing() != 0) {
    _this->_internal_set_ongoing(from._internal_ongoing());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TimeUpdate::CopyFrom(const TimeUpdate& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yass.fs.TimeUpdate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TimeUpdate::IsInitialized() const {
  return true;
}

void TimeUpdate::InternalSwap(TimeUpdate* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TimeUpdate, _impl_.ongoing_)
      + sizeof(TimeUpdate::_impl_.ongoing_)
      - PROTOBUF_FIELD_OFFSET(TimeUpdate, _impl_.now_)>(
          reinterpret_cast<char*>(&_impl_.now_),
          reinterpret_cast<char*>(&other->_impl_.now_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TimeUpdate::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_time_5fupdate_2eproto_getter, &descriptor_table_time_5fupdate_2eproto_once,
      file_level_metadata_time_5fupdate_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace fs
}  // namespace yass
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::yass::fs::TimeUpdate*
Arena::CreateMaybeMessage< ::yass::fs::TimeUpdate >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yass::fs::TimeUpdate >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
