version: '3'

vars:
  TAG:
    sh: |
      v=$(git describe --tags --exact-match 2>/dev/null || true)
      if [ -n "$v" ]; then echo "${v#v}";
      elif s=$(git rev-parse --short=8 HEAD 2>/dev/null); then echo "${s}";
      else date '+%Y%m%dt%H%M%S'; fi
  IMG: 'ghcr.io/duobitx/yass-operator'

tasks:
  default:
    desc: Build and push
    cmds:
      - task: build
      - task: push

  build:
    desc: Generate manifests, installer YAML, and helm chart
    cmds:
      - make build-installer IMG={{.IMG}}
      - make helm-chart IMG={{.IMG}}

  push:
    desc: Build & push Docker image
    cmds:
      # FIXME - make docker-buildx
      - make docker-build IMG={{.IMG}}
      - make docker-push IMG={{.IMG}}
      - 'echo "📦 pushed {{.IMG}}"'
      - docker tag {{.IMG}} {{.IMG}}:{{.TAG}}
      - make docker-push IMG={{.IMG}}:{{.TAG}}
      - 'echo "📦 pushed {{.IMG}}:{{.TAG}}"'

  help:
    desc: Display Makefile help
    cmds:
      - make help

  make:
    desc: "Run any Makefile target (example: task make -- test)"
    cmds:
      - make {{.CLI_ARGS}}
