version: '3'

vars:
  VERSION:
    sh: "v=$(git describe --tags --exact-match 2>/dev/null || true); if [ -n \"$v\" ]; then echo \"${v#v}\"; else echo latest; fi"
  IMG: 'ghcr.io/duobitx/yass-operator:{{.VERSION}}'

tasks:
  default:
    desc: Build and push
    cmds:
      - task: build
      - task: push

  build:
    desc: Build
    cmds:
      - make IMG={{.IMG}}
      - make build-installer IMG={{.IMG}}
      - make helm-chart IMG={{.IMG}}

  push:
    desc: Push
    cmds:
      # FIXME - make docker-buildx
      - make docker-build IMG={{.IMG}}
      - make docker-push IMG={{.IMG}}
      - 'echo "📦 pushed {{.IMG}}"'

  help:
    desc: Display Makefile help
    cmds:
      - make help

  make:
    desc: "Run any Makefile target (example: task make -- test)"
    cmds:
      - make {{.CLI_ARGS}}
