// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: geocalc_message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	X             float64                `protobuf:"fixed64,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,4,opt,name=y,proto3" json:"y,omitempty"`
	Z             float64                `protobuf:"fixed64,5,opt,name=z,proto3" json:"z,omitempty"`
	Lat           float64                `protobuf:"fixed64,6,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,7,opt,name=lon,proto3" json:"lon,omitempty"`
	Alt           float64                `protobuf:"fixed64,8,opt,name=alt,proto3" json:"alt,omitempty"`
	InTheSun      bool                   `protobuf:"varint,9,opt,name=in_the_sun,json=inTheSun,proto3" json:"in_the_sun,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_geocalc_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_geocalc_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_geocalc_message_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Item) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Item) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *Item) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Item) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *Item) GetAlt() float64 {
	if x != nil {
		return x.Alt
	}
	return 0
}

func (x *Item) GetInTheSun() bool {
	if x != nil {
		return x.InTheSun
	}
	return false
}

type Distance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemIdA       int32                  `protobuf:"varint,1,opt,name=item_id_a,json=itemIdA,proto3" json:"item_id_a,omitempty"`
	ItemIdB       int32                  `protobuf:"varint,2,opt,name=item_id_b,json=itemIdB,proto3" json:"item_id_b,omitempty"`
	Distance      float32                `protobuf:"fixed32,3,opt,name=distance,proto3" json:"distance,omitempty"`
	Los           bool                   `protobuf:"varint,4,opt,name=los,proto3" json:"los,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Distance) Reset() {
	*x = Distance{}
	mi := &file_geocalc_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Distance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Distance) ProtoMessage() {}

func (x *Distance) ProtoReflect() protoreflect.Message {
	mi := &file_geocalc_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Distance.ProtoReflect.Descriptor instead.
func (*Distance) Descriptor() ([]byte, []int) {
	return file_geocalc_message_proto_rawDescGZIP(), []int{1}
}

func (x *Distance) GetItemIdA() int32 {
	if x != nil {
		return x.ItemIdA
	}
	return 0
}

func (x *Distance) GetItemIdB() int32 {
	if x != nil {
		return x.ItemIdB
	}
	return 0
}

func (x *Distance) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *Distance) GetLos() bool {
	if x != nil {
		return x.Los
	}
	return false
}

type GeoCommon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nsat          int32                  `protobuf:"varint,1,opt,name=nsat,proto3" json:"nsat,omitempty"`
	Nbs           int32                  `protobuf:"varint,2,opt,name=nbs,proto3" json:"nbs,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	Items         []*Item                `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	Distances     []*Distance            `protobuf:"bytes,5,rep,name=distances,proto3" json:"distances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoCommon) Reset() {
	*x = GeoCommon{}
	mi := &file_geocalc_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoCommon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoCommon) ProtoMessage() {}

func (x *GeoCommon) ProtoReflect() protoreflect.Message {
	mi := &file_geocalc_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoCommon.ProtoReflect.Descriptor instead.
func (*GeoCommon) Descriptor() ([]byte, []int) {
	return file_geocalc_message_proto_rawDescGZIP(), []int{2}
}

func (x *GeoCommon) GetNsat() int32 {
	if x != nil {
		return x.Nsat
	}
	return 0
}

func (x *GeoCommon) GetNbs() int32 {
	if x != nil {
		return x.Nbs
	}
	return 0
}

func (x *GeoCommon) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *GeoCommon) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GeoCommon) GetDistances() []*Distance {
	if x != nil {
		return x.Distances
	}
	return nil
}

var File_geocalc_message_proto protoreflect.FileDescriptor

var file_geocalc_message_proto_rawDesc = string([]byte{
	0x0a, 0x15, 0x67, 0x65, 0x6f, 0x63, 0x61, 0x6c, 0x63, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x79, 0x61, 0x73, 0x73, 0x2e, 0x66, 0x73,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xa8, 0x01, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0c,
	0x0a, 0x01, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x7a, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f,
	0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03,
	0x61, 0x6c, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x61, 0x6c, 0x74, 0x12, 0x1c,
	0x0a, 0x0a, 0x69, 0x6e, 0x5f, 0x74, 0x68, 0x65, 0x5f, 0x73, 0x75, 0x6e, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x69, 0x6e, 0x54, 0x68, 0x65, 0x53, 0x75, 0x6e, 0x22, 0x70, 0x0a, 0x08,
	0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x09, 0x69, 0x74, 0x65, 0x6d,
	0x5f, 0x69, 0x64, 0x5f, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x69, 0x74, 0x65,
	0x6d, 0x49, 0x64, 0x41, 0x12, 0x1a, 0x0a, 0x09, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x5f,
	0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x42,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6c, 0x6f, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x6c, 0x6f, 0x73, 0x22, 0xb7,
	0x01, 0x0a, 0x09, 0x47, 0x65, 0x6f, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x73, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6e, 0x73, 0x61, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6e, 0x62, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e,
	0x62, 0x73, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x79, 0x61, 0x73, 0x73, 0x2e, 0x66, 0x73, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x2f, 0x0a, 0x09, 0x64, 0x69, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x79, 0x61, 0x73,
	0x73, 0x2e, 0x66, 0x73, 0x2e, 0x44, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x09, 0x64,
	0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x42, 0x43, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x75, 0x6f, 0x62, 0x69, 0x74, 0x78, 0x2f, 0x79,
	0x61, 0x73, 0x73, 0x2d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2d, 0x63, 0x6f, 0x6d,
	0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x67, 0x6f, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_geocalc_message_proto_rawDescOnce sync.Once
	file_geocalc_message_proto_rawDescData []byte
)

func file_geocalc_message_proto_rawDescGZIP() []byte {
	file_geocalc_message_proto_rawDescOnce.Do(func() {
		file_geocalc_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geocalc_message_proto_rawDesc), len(file_geocalc_message_proto_rawDesc)))
	})
	return file_geocalc_message_proto_rawDescData
}

var file_geocalc_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_geocalc_message_proto_goTypes = []any{
	(*Item)(nil),                  // 0: yass.fs.Item
	(*Distance)(nil),              // 1: yass.fs.Distance
	(*GeoCommon)(nil),             // 2: yass.fs.GeoCommon
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_geocalc_message_proto_depIdxs = []int32{
	3, // 0: yass.fs.GeoCommon.time:type_name -> google.protobuf.Timestamp
	0, // 1: yass.fs.GeoCommon.items:type_name -> yass.fs.Item
	1, // 2: yass.fs.GeoCommon.distances:type_name -> yass.fs.Distance
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_geocalc_message_proto_init() }
func file_geocalc_message_proto_init() {
	if File_geocalc_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geocalc_message_proto_rawDesc), len(file_geocalc_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_geocalc_message_proto_goTypes,
		DependencyIndexes: file_geocalc_message_proto_depIdxs,
		MessageInfos:      file_geocalc_message_proto_msgTypes,
	}.Build()
	File_geocalc_message_proto = out.File
	file_geocalc_message_proto_goTypes = nil
	file_geocalc_message_proto_depIdxs = nil
}
